insert into cliente (nome, indirizzo) values ('Kincaid Lidgley', '1808 Starling Court');
insert into cliente (nome, indirizzo) values ('Linette Aitchison', '31 Dorton Avenue');
insert into cliente (nome, indirizzo) values ('Margette Jirousek', '6 Susan Trail');
insert into cliente (nome, indirizzo) values ('Will Purdie', '1 Briar Crest Point');
insert into cliente (nome, indirizzo) values ('Benito Congrave', '4128 Florence Plaza');
insert into cliente (nome, indirizzo) values ('Care Tomasek', '280 Dexter Hill');
insert into cliente (nome, indirizzo) values ('Elsinore Smallpeice', '338 Jana Road');
insert into cliente (nome, indirizzo) values ('Eduardo Janosevic', '2385 Huxley Point');
insert into cliente (nome, indirizzo) values ('Kahlil Sloyan', '3 Fairfield Place');
insert into cliente (nome, indirizzo) values ('Ansley Kopfen', '6204 Forest Street');
insert into cliente (nome, indirizzo) values ('Willyt Batting', '6505 Graedel Trail');
insert into cliente (nome, indirizzo) values ('Larissa Schwandermann', '460 Mariners Cove Hill');
insert into cliente (nome, indirizzo) values ('Brandais Maskrey', '1 Springs Point');
insert into cliente (nome, indirizzo) values ('Mirna Tarply', '6575 Waxwing Lane');
insert into cliente (nome, indirizzo) values ('Mario Chesswas', '95408 3rd Pass');
insert into cliente (nome, indirizzo) values ('Nicolle Fausset', '28 Oneill Pass');
insert into cliente (nome, indirizzo) values ('Garwood Sigward', '88 Pearson Park');
insert into cliente (nome, indirizzo) values ('Hildegaard Neil', '484 Jenna Avenue');
insert into cliente (nome, indirizzo) values ('Vance Darwen', '3 Gale Street');
insert into cliente (nome, indirizzo) values ('Allister Badrick', '92126 Manitowish Terrace');
insert into cliente (nome, indirizzo) values ('Micky Maides', '55375 Rutledge Drive');
insert into cliente (nome, indirizzo) values ('Nikolos Jurgenson', '764 Granby Terrace');
insert into cliente (nome, indirizzo) values ('Dorothy Rooksby', '87366 Columbus Trail');
insert into cliente (nome, indirizzo) values ('Benedetta Tregenza', '0810 Basil Trail');
insert into cliente (nome, indirizzo) values ('Llywellyn Drioli', '6 Almo Center');
insert into cliente (nome, indirizzo) values ('Jorie Hess', '018 Lukken Crossing');
insert into cliente (nome, indirizzo) values ('Stephenie Pagin', '4 Mandrake Place');
insert into cliente (nome, indirizzo) values ('Codi Gaudin', '183 Buhler Alley');
insert into cliente (nome, indirizzo) values ('Kerr Fudger', '21 Dakota Point');
insert into cliente (nome, indirizzo) values ('Kevan Hynde', '38 Vernon Crossing');
insert into cliente (nome, indirizzo) values ('Halsy Calvard', '11721 Lerdahl Street');
insert into cliente (nome, indirizzo) values ('Winfred Conaboy', '0651 Crest Line Lane');
insert into cliente (nome, indirizzo) values ('Rena Rosander', '10950 Hanson Court');
insert into cliente (nome, indirizzo) values ('Freddie Bilbrey', '20531 Steensland Court');
insert into cliente (nome, indirizzo) values ('Ursula Janse', '5506 Laurel Crossing');
insert into cliente (nome, indirizzo) values ('Brooks Benallack', '6 Schurz Road');
insert into cliente (nome, indirizzo) values ('Halley Gresley', '4 Manufacturers Way');
insert into cliente (nome, indirizzo) values ('Oneida Burdas', '57420 Buell Pass');
insert into cliente (nome, indirizzo) values ('Alleyn Darrow', '378 Everett Court');
insert into cliente (nome, indirizzo) values ('Karlene Ireland', '08094 Anzinger Place');
insert into cliente (nome, indirizzo) values ('Chris Parlor', '8426 Sachs Lane');
insert into cliente (nome, indirizzo) values ('Mahmud Cheltnam', '5 Dennis Trail');
insert into cliente (nome, indirizzo) values ('Bobbee Devons', '7806 Rigney Circle');
insert into cliente (nome, indirizzo) values ('Hatty Bockett', '415 Sommers Point');
insert into cliente (nome, indirizzo) values ('Neysa Kipping', '4 Cottonwood Point');
insert into cliente (nome, indirizzo) values ('Javier Masham', '59 Sherman Drive');
insert into cliente (nome, indirizzo) values ('Odelle Haverson', '1482 La Follette Road');
insert into cliente (nome, indirizzo) values ('Reamonn Dullaghan', '4 Shoshone Way');
insert into cliente (nome, indirizzo) values ('Tome Canceller', '9716 Graedel Avenue');
insert into cliente (nome, indirizzo) values ('Eloise Worton', '0 Nevada Road');
insert into cliente (nome, indirizzo) values ('Belle Boydell', '5 Riverside Alley');
insert into cliente (nome, indirizzo) values ('Laurianne Bleeze', '1809 3rd Parkway');
insert into cliente (nome, indirizzo) values ('Jacynth Shirlaw', '94 Fairfield Park');
insert into cliente (nome, indirizzo) values ('Myrta Keinrat', '473 Golden Leaf Park');
insert into cliente (nome, indirizzo) values ('Willi Eddins', '1059 Maple Avenue');
insert into cliente (nome, indirizzo) values ('Henderson MacConnechie', '264 Buell Circle');
insert into cliente (nome, indirizzo) values ('Alexander Larrat', '8414 Cascade Avenue');
insert into cliente (nome, indirizzo) values ('Jameson Suckling', '39132 Erie Crossing');
insert into cliente (nome, indirizzo) values ('Debbie Ludlam', '0882 Bay Court');
insert into cliente (nome, indirizzo) values ('Timmi Felkin', '446 Walton Pass');
insert into cliente (nome, indirizzo) values ('Lavina Yoell', '5 Wayridge Hill');
insert into cliente (nome, indirizzo) values ('Torie Cruickshank', '30346 Westridge Center');
insert into cliente (nome, indirizzo) values ('Ulrikaumeko Baline', '361 Logan Terrace');
insert into cliente (nome, indirizzo) values ('Phyllida Acomb', '7 Carpenter Parkway');
insert into cliente (nome, indirizzo) values ('Roderich Berisford', '08408 Vernon Way');
insert into cliente (nome, indirizzo) values ('Julio Maker', '0 Harper Crossing');
insert into cliente (nome, indirizzo) values ('Una Laughnan', '44 Ridgeview Place');
insert into cliente (nome, indirizzo) values ('Ranee Albion', '873 Summer Ridge Point');
insert into cliente (nome, indirizzo) values ('Mano Bottelstone', '752 Prairie Rose Way');
insert into cliente (nome, indirizzo) values ('Neddy Scaplehorn', '9720 David Place');
insert into cliente (nome, indirizzo) values ('Adah Matussov', '0554 Gateway Crossing');
insert into cliente (nome, indirizzo) values ('Donia Norvell', '88 Nelson Terrace');
insert into cliente (nome, indirizzo) values ('Lydia Ferrarin', '71 Scott Alley');
insert into cliente (nome, indirizzo) values ('Paulie Bursell', '10 Gateway Court');
insert into cliente (nome, indirizzo) values ('Karolina Ormerod', '17 Division Lane');
insert into cliente (nome, indirizzo) values ('Davin Brandrick', '6 Lukken Junction');
insert into cliente (nome, indirizzo) values ('Lion Mitten', '0 Beilfuss Point');
insert into cliente (nome, indirizzo) values ('Glyn Lax', '0 Huxley Terrace');
insert into cliente (nome, indirizzo) values ('Ozzy Ruckert', '194 Grover Plaza');
insert into cliente (nome, indirizzo) values ('Fredrick Fishleigh', '56 Village Green Trail');
insert into cliente (nome, indirizzo) values ('Jorge Thieme', '5912 7th Crossing');
insert into cliente (nome, indirizzo) values ('Perren Semper', '7 Loeprich Parkway');
insert into cliente (nome, indirizzo) values ('Bennie Janiszewski', '41609 Nelson Lane');
insert into cliente (nome, indirizzo) values ('Louis Doding', '9157 Loomis Avenue');
insert into cliente (nome, indirizzo) values ('Kacie Hebblethwaite', '6588 Commercial Court');
insert into cliente (nome, indirizzo) values ('Sandor Dews', '355 Hollow Ridge Point');
insert into cliente (nome, indirizzo) values ('Joyann Luckhurst', '5901 Dakota Crossing');
insert into cliente (nome, indirizzo) values ('Cassie Edelheid', '5945 Hermina Plaza');
insert into cliente (nome, indirizzo) values ('Saba Brine', '55974 Ridge Oak Drive');
insert into cliente (nome, indirizzo) values ('Jacqui McIlharga', '8040 Forest Run Parkway');
insert into cliente (nome, indirizzo) values ('Wesley Grzelczyk', '8 Jana Street');
insert into cliente (nome, indirizzo) values ('Adham Rockhill', '2 Bonner Point');
insert into cliente (nome, indirizzo) values ('Colas Phear', '7 Forest Run Junction');
insert into cliente (nome, indirizzo) values ('Brittney Standring', '03 Mifflin Pass');
insert into cliente (nome, indirizzo) values ('Con Lemin', '647 Anthes Court');
insert into cliente (nome, indirizzo) values ('Constantia Filipponi', '4 Lillian Parkway');
insert into cliente (nome, indirizzo) values ('Cammy Southwood', '0 Brentwood Court');
insert into cliente (nome, indirizzo) values ('Madlen Waison', '2 Meadow Vale Place');
insert into cliente (nome, indirizzo) values ('Adams Deakins', '225 Waubesa Trail');
insert into cliente (nome, indirizzo) values ('Archambault Denne', '483 Pond Road');
insert into cliente (nome, indirizzo) values ('Maxi Rikel', '1 Marcy Point');
insert into cliente (nome, indirizzo) values ('Jimmy Novichenko', '32520 Northwestern Avenue');
insert into cliente (nome, indirizzo) values ('Levin Melton', '116 Magdeline Avenue');
insert into cliente (nome, indirizzo) values ('Cornell Espinola', '2 Redwing Pass');
insert into cliente (nome, indirizzo) values ('Jacynth Pumphrey', '07603 Spohn Lane');
insert into cliente (nome, indirizzo) values ('Garik Starmer', '064 Hooker Circle');
insert into cliente (nome, indirizzo) values ('Freddie Astling', '3 Hintze Parkway');
insert into cliente (nome, indirizzo) values ('Yul Kuhnert', '18687 Division Plaza');
insert into cliente (nome, indirizzo) values ('Nicole Sessions', '69 Sugar Hill');
insert into cliente (nome, indirizzo) values ('Nappie Sycamore', '2779 Kipling Center');
insert into cliente (nome, indirizzo) values ('Daisi Gludor', '677 Farragut Road');
insert into cliente (nome, indirizzo) values ('Candis Hew', '531 Graceland Plaza');
insert into cliente (nome, indirizzo) values ('Robby Thuillier', '849 Alpine Street');
insert into cliente (nome, indirizzo) values ('Storm Babinski', '625 Pearson Park');
insert into cliente (nome, indirizzo) values ('Dill Askell', '3 Holy Cross Junction');
insert into cliente (nome, indirizzo) values ('Mano Spilstead', '0 Dunning Center');
insert into cliente (nome, indirizzo) values ('Tracy MacHoste', '6 Spohn Lane');
insert into cliente (nome, indirizzo) values ('Christabel Thys', '35839 Northview Trail');
insert into cliente (nome, indirizzo) values ('Elisabeth Mongenot', '4 Anniversary Drive');
insert into cliente (nome, indirizzo) values ('Wilek Nowlan', '981 La Follette Court');
insert into cliente (nome, indirizzo) values ('Esmeralda Dowderswell', '22767 Carpenter Park');
insert into cliente (nome, indirizzo) values ('Rowen Tallyn', '740 Brown Circle');
insert into cliente (nome, indirizzo) values ('Jeth Hughland', '77872 Monterey Trail');
insert into cliente (nome, indirizzo) values ('Drake Harmon', '61393 Wayridge Avenue');
insert into cliente (nome, indirizzo) values ('Sibylla Jatczak', '4007 Westport Drive');
insert into cliente (nome, indirizzo) values ('Rawley Antos', '7 Morningstar Road');
insert into cliente (nome, indirizzo) values ('Willy Jaffray', '3 Sugar Street');
insert into cliente (nome, indirizzo) values ('Ronda Heugle', '9 Sommers Alley');
insert into cliente (nome, indirizzo) values ('Thornie McCrillis', '6535 Cambridge Point');
insert into cliente (nome, indirizzo) values ('Jerrine Flisher', '15794 Pawling Plaza');
insert into cliente (nome, indirizzo) values ('Silvan Kirkam', '17176 Browning Crossing');
insert into cliente (nome, indirizzo) values ('Gabbey Le Gallo', '00 Summerview Drive');
insert into cliente (nome, indirizzo) values ('Rupert Pepis', '6985 Messerschmidt Point');
insert into cliente (nome, indirizzo) values ('Alameda Aveyard', '6 Pankratz Road');
insert into cliente (nome, indirizzo) values ('Sonnie Manby', '81 Dexter Alley');
insert into cliente (nome, indirizzo) values ('Leena Cory', '48 Pleasure Avenue');
insert into cliente (nome, indirizzo) values ('Ange Prew', '283 Bunker Hill Drive');
insert into cliente (nome, indirizzo) values ('Ignace Zoren', '47 Graedel Circle');
insert into cliente (nome, indirizzo) values ('Jemimah Eicke', '5 Autumn Leaf Plaza');
insert into cliente (nome, indirizzo) values ('Pennie Sheldon', '72847 Ryan Road');
insert into cliente (nome, indirizzo) values ('Madella Mergue', '680 Moose Plaza');
insert into cliente (nome, indirizzo) values ('Ulick Denness', '1867 Harbort Way');
insert into cliente (nome, indirizzo) values ('Odelle Luffman', '27208 Northview Terrace');
insert into cliente (nome, indirizzo) values ('Percy Knighton', '86770 Quincy Park');
insert into cliente (nome, indirizzo) values ('Josiah Ash', '27400 Dennis Trail');
insert into cliente (nome, indirizzo) values ('Osbourn Tustin', '52358 Anderson Point');
insert into cliente (nome, indirizzo) values ('Candida Barwis', '90530 Springs Circle');
insert into cliente (nome, indirizzo) values ('Lorrin Bodicum', '90 Orin Street');
insert into cliente (nome, indirizzo) values ('Ellsworth Newport', '4 Starling Crossing');
insert into cliente (nome, indirizzo) values ('Johnathon Spurett', '7617 Beilfuss Plaza');
insert into cliente (nome, indirizzo) values ('Rodrick Ruxton', '00 Union Park');
insert into cliente (nome, indirizzo) values ('Foss Friday', '25511 Anderson Drive');
insert into cliente (nome, indirizzo) values ('Colly Parnham', '1 Dennis Place');
insert into cliente (nome, indirizzo) values ('Bondon Briat', '4 David Center');
insert into cliente (nome, indirizzo) values ('Nanci Brandenberg', '5 Myrtle Terrace');
insert into cliente (nome, indirizzo) values ('Cristy McVeigh', '60 Pennsylvania Junction');
insert into cliente (nome, indirizzo) values ('Corbett Kehir', '7265 Anzinger Avenue');
insert into cliente (nome, indirizzo) values ('Zenia Humfrey', '3201 Walton Park');
insert into cliente (nome, indirizzo) values ('Augy Uren', '5383 Comanche Pass');
insert into cliente (nome, indirizzo) values ('Ben Cornfield', '61523 Arrowood Junction');
insert into cliente (nome, indirizzo) values ('Del Endacott', '460 David Hill');
insert into cliente (nome, indirizzo) values ('Ediva Kaser', '47 Arizona Way');
insert into cliente (nome, indirizzo) values ('Antoinette MacKaig', '082 Merchant Trail');
insert into cliente (nome, indirizzo) values ('Melita Sergent', '7298 Prairieview Terrace');
insert into cliente (nome, indirizzo) values ('Mufi Dur', '4444 Hermina Trail');
insert into cliente (nome, indirizzo) values ('Penn Shipperbottom', '65 School Park');
insert into cliente (nome, indirizzo) values ('Philippine Fearnyhough', '17 Portage Lane');
insert into cliente (nome, indirizzo) values ('Adrien Strewthers', '05 Becker Pass');
insert into cliente (nome, indirizzo) values ('Debbie Aindrais', '33169 Namekagon Avenue');
insert into cliente (nome, indirizzo) values ('Kandace Ranyard', '554 Prairie Rose Court');
insert into cliente (nome, indirizzo) values ('Lucius Kuhnert', '42135 Garrison Hill');
insert into cliente (nome, indirizzo) values ('Andreas Scala', '7 Hanover Street');
insert into cliente (nome, indirizzo) values ('Lucy Pretorius', '0 Montana Plaza');
insert into cliente (nome, indirizzo) values ('Raymund Dafforne', '7055 Algoma Point');
insert into cliente (nome, indirizzo) values ('Gabriellia Bricket', '63295 Valley Edge Circle');
insert into cliente (nome, indirizzo) values ('Lauren McDuffy', '6496 Dapin Road');
insert into cliente (nome, indirizzo) values ('Jorey Currin', '81954 4th Court');
insert into cliente (nome, indirizzo) values ('Barrie Longfoot', '73080 Nobel Parkway');
insert into cliente (nome, indirizzo) values ('Elyn Adolfsen', '121 6th Parkway');
insert into cliente (nome, indirizzo) values ('Roosevelt Toderini', '032 Artisan Park');
insert into cliente (nome, indirizzo) values ('Imojean Brun', '9000 Sauthoff Trail');
insert into cliente (nome, indirizzo) values ('Charlotte Kember', '21474 Homewood Point');
insert into cliente (nome, indirizzo) values ('Norah Bartelli', '96 Cardinal Pass');
insert into cliente (nome, indirizzo) values ('Nani Cargill', '66 Del Sol Terrace');
insert into cliente (nome, indirizzo) values ('Marlena Dudmesh', '6 Forest Dale Plaza');
insert into cliente (nome, indirizzo) values ('Chaddie Barwood', '372 Buhler Junction');
insert into cliente (nome, indirizzo) values ('Maryellen Korpal', '9617 Moose Avenue');
insert into cliente (nome, indirizzo) values ('Fonz Anthoin', '1 Roth Pass');
insert into cliente (nome, indirizzo) values ('Oliviero Mushrow', '2 Jenna Plaza');
insert into cliente (nome, indirizzo) values ('Shelton Matijevic', '31708 Nelson Plaza');
insert into cliente (nome, indirizzo) values ('Jenifer Widdowson', '1295 Ridgeway Crossing');
insert into cliente (nome, indirizzo) values ('Dickie Fickling', '79839 Burrows Drive');
insert into cliente (nome, indirizzo) values ('Marja Wike', '9 Aberg Park');
insert into cliente (nome, indirizzo) values ('Sybil Cicchitello', '07724 Maryland Terrace');
insert into cliente (nome, indirizzo) values ('Jerrilyn Oke', '57352 Northview Avenue');
insert into cliente (nome, indirizzo) values ('Dalton Walework', '37578 Arkansas Circle');
insert into cliente (nome, indirizzo) values ('Marnia Marshal', '8410 Maywood Lane');
insert into cliente (nome, indirizzo) values ('Joellyn Ambrogini', '818 Sauthoff Plaza');
insert into cliente (nome, indirizzo) values ('Chicky Sixsmith', '0 Division Plaza');
insert into cliente (nome, indirizzo) values ('Anneliese Jerram', '35 Morrow Parkway');
insert into cliente (nome, indirizzo) values ('Tim Waberer', '5497 Summer Ridge Parkway');
insert into cliente (nome, indirizzo) values ('Lynett Badger', '905 Debs Plaza');
insert into cliente (nome, indirizzo) values ('Umberto Castel', '10908 Mendota Point');
insert into cliente (nome, indirizzo) values ('Betti Avard', '8586 Blackbird Center');
insert into cliente (nome, indirizzo) values ('Maury McNeillie', '91610 Park Meadow Avenue');
insert into cliente (nome, indirizzo) values ('Mufinella Latch', '8940 Ridge Oak Road');
insert into cliente (nome, indirizzo) values ('Elmer Filimore', '37385 Barby Plaza');
insert into cliente (nome, indirizzo) values ('Schuyler Rammell', '72716 Banding Junction');
insert into cliente (nome, indirizzo) values ('Lonnie Shoard', '076 Westerfield Hill');
insert into cliente (nome, indirizzo) values ('Kariotta Mauro', '1110 Acker Drive');
insert into cliente (nome, indirizzo) values ('Berni Emnoney', '044 Killdeer Place');
insert into cliente (nome, indirizzo) values ('Lavina Novak', '98656 Sommers Park');
insert into cliente (nome, indirizzo) values ('Ryley Dowbiggin', '7089 Hallows Place');
insert into cliente (nome, indirizzo) values ('Hamnet Ebbitt', '5 Heffernan Place');
insert into cliente (nome, indirizzo) values ('Jennilee Fleisch', '876 Kipling Pass');
insert into cliente (nome, indirizzo) values ('Catarina Laminman', '76 5th Terrace');
insert into cliente (nome, indirizzo) values ('Belicia Capun', '20 Park Meadow Way');
insert into cliente (nome, indirizzo) values ('Zaneta Malley', '0065 American Ash Circle');
insert into cliente (nome, indirizzo) values ('Felipe Sybbe', '91 Algoma Park');
insert into cliente (nome, indirizzo) values ('Alexandr Westmoreland', '5952 Scofield Terrace');
insert into cliente (nome, indirizzo) values ('Shanda Seelbach', '32863 Arrowood Lane');
insert into cliente (nome, indirizzo) values ('Hilliary Pirot', '67 Anhalt Lane');
insert into cliente (nome, indirizzo) values ('Lauralee Crowley', '96 Hoffman Crossing');
insert into cliente (nome, indirizzo) values ('Vivyan Rheaume', '99 Melody Road');
insert into cliente (nome, indirizzo) values ('Egan Over', '41 West Park');
insert into cliente (nome, indirizzo) values ('Allix Smiz', '36134 Farragut Pass');
insert into cliente (nome, indirizzo) values ('Amie Dow', '0 Loomis Crossing');
insert into cliente (nome, indirizzo) values ('Elinor Allmond', '73 Roth Pass');
insert into cliente (nome, indirizzo) values ('Lexie Kinghorne', '3661 Green Ridge Plaza');
insert into cliente (nome, indirizzo) values ('Ora Pryce', '91 Grover Lane');
insert into cliente (nome, indirizzo) values ('Annamaria Ogilvy', '64 Loeprich Hill');
insert into cliente (nome, indirizzo) values ('Christoper Sendall', '594 Schlimgen Parkway');
insert into cliente (nome, indirizzo) values ('Emily Roon', '86 Prairieview Court');
insert into cliente (nome, indirizzo) values ('Aubrey Thouless', '14383 Ruskin Junction');
insert into cliente (nome, indirizzo) values ('Hedwiga Battams', '5416 Lindbergh Avenue');
insert into cliente (nome, indirizzo) values ('Arni Defond', '05 Thackeray Point');
insert into cliente (nome, indirizzo) values ('Allie Ambroz', '4 Division Center');
insert into cliente (nome, indirizzo) values ('Marybelle Orrill', '8 Nelson Park');
insert into cliente (nome, indirizzo) values ('Fey Andreacci', '105 Ridgeway Park');
insert into cliente (nome, indirizzo) values ('Benedicta Lazar', '5833 Westend Trail');
insert into cliente (nome, indirizzo) values ('Ellyn Attwell', '2 North Road');
insert into cliente (nome, indirizzo) values ('Peggi McGirl', '271 Sundown Circle');
insert into cliente (nome, indirizzo) values ('Lucine Tipper', '06501 Victoria Parkway');
insert into cliente (nome, indirizzo) values ('Rob Glantz', '662 Melrose Drive');
insert into cliente (nome, indirizzo) values ('Odetta Olpin', '77965 Sommers Point');
insert into cliente (nome, indirizzo) values ('Verney Brumham', '517 Eastwood Way');
insert into cliente (nome, indirizzo) values ('Blondie Tettersell', '073 Dixon Point');
insert into cliente (nome, indirizzo) values ('Pace Hyne', '1 Hallows Parkway');
insert into cliente (nome, indirizzo) values ('Vincenty Limming', '2 Melrose Plaza');
insert into cliente (nome, indirizzo) values ('Danni Bonaire', '7671 Sunnyside Terrace');
insert into cliente (nome, indirizzo) values ('Lena Urlin', '3 Kensington Lane');
insert into cliente (nome, indirizzo) values ('Zacherie Dabes', '0670 Petterle Court');
insert into cliente (nome, indirizzo) values ('Faustina Pickworth', '4982 Darwin Court');
insert into cliente (nome, indirizzo) values ('Wynnie Swanger', '61 Hollow Ridge Terrace');
insert into cliente (nome, indirizzo) values ('Niki Brundale', '46 Sutteridge Court');
insert into cliente (nome, indirizzo) values ('Beatriz St Louis', '24584 Straubel Drive');
insert into cliente (nome, indirizzo) values ('Pavel MacBrearty', '4017 3rd Way');
insert into cliente (nome, indirizzo) values ('Charlotta Maden', '744 Bartillon Park');
insert into cliente (nome, indirizzo) values ('Caroline Nassey', '3 Fair Oaks Way');
insert into cliente (nome, indirizzo) values ('Perkin Grgic', '3642 Dennis Terrace');
insert into cliente (nome, indirizzo) values ('Christean Iacovazzi', '3714 Milwaukee Plaza');
insert into cliente (nome, indirizzo) values ('Philis Spowage', '76 Dixon Terrace');
insert into cliente (nome, indirizzo) values ('Basil Filipovic', '90 4th Crossing');
insert into cliente (nome, indirizzo) values ('Nickolai Bausmann', '95 Roxbury Pass');
insert into cliente (nome, indirizzo) values ('Daron Archbald', '87558 Sutherland Road');
insert into cliente (nome, indirizzo) values ('Natasha Cornelisse', '227 5th Street');
insert into cliente (nome, indirizzo) values ('Zarah Gliddon', '2 Swallow Drive');
insert into cliente (nome, indirizzo) values ('Nana Tilmouth', '28 Lake View Terrace');
insert into cliente (nome, indirizzo) values ('Madonna Doers', '7 Basil Plaza');
insert into cliente (nome, indirizzo) values ('Linette Walliker', '9284 Declaration Hill');
insert into cliente (nome, indirizzo) values ('Tabitha Mate', '11 Fairview Circle');
insert into cliente (nome, indirizzo) values ('Augustus Reymers', '064 Pearson Alley');
insert into cliente (nome, indirizzo) values ('Marshall Tipperton', '14834 Lerdahl Crossing');
insert into cliente (nome, indirizzo) values ('Nicolea Jewson', '023 International Road');
insert into cliente (nome, indirizzo) values ('Felisha Ruddiman', '40 Vera Circle');
insert into cliente (nome, indirizzo) values ('Hilton Piotr', '5048 Eagle Crest Hill');
insert into cliente (nome, indirizzo) values ('Zonnya Book', '3411 Arkansas Plaza');
insert into cliente (nome, indirizzo) values ('Keefe Camings', '17 Glendale Street');
insert into cliente (nome, indirizzo) values ('Raquela Rosnau', '02746 Menomonie Pass');
insert into cliente (nome, indirizzo) values ('Tanya Ullett', '8 Lukken Avenue');
insert into cliente (nome, indirizzo) values ('Odella Davies', '554 Badeau Street');
insert into cliente (nome, indirizzo) values ('Chaddie Warry', '91010 Merchant Street');
insert into cliente (nome, indirizzo) values ('Meredith Pimley', '11 Ludington Crossing');
insert into cliente (nome, indirizzo) values ('Roxana Eplate', '72 6th Circle');
insert into cliente (nome, indirizzo) values ('Ado Harpin', '4620 Fulton Street');
insert into cliente (nome, indirizzo) values ('Heddi Murgatroyd', '02 Pepper Wood Circle');
insert into cliente (nome, indirizzo) values ('Rochester Berns', '1751 Becker Lane');
insert into cliente (nome, indirizzo) values ('Darrelle Riccard', '11 Barby Parkway');
insert into cliente (nome, indirizzo) values ('Randie Nockles', '88345 Riverside Circle');
insert into cliente (nome, indirizzo) values ('Antoine Duncan', '45 Prairieview Lane');
insert into cliente (nome, indirizzo) values ('Nicole Cutbush', '76 New Castle Terrace');
insert into cliente (nome, indirizzo) values ('Arlinda Baumaier', '40288 Spenser Circle');
insert into cliente (nome, indirizzo) values ('Arie Filochov', '8 Burning Wood Park');
insert into cliente (nome, indirizzo) values ('Briana Lyenyng', '63 Spenser Pass');
insert into cliente (nome, indirizzo) values ('Audra Petegre', '820 Sunfield Park');
insert into cliente (nome, indirizzo) values ('Lacie Volke', '57073 Dexter Hill');
insert into cliente (nome, indirizzo) values ('Jean Culpen', '672 Amoth Place');
insert into cliente (nome, indirizzo) values ('Frannie Matthius', '93008 Crownhardt Street');
insert into cliente (nome, indirizzo) values ('Cooper Gaskamp', '24169 Knutson Court');
insert into cliente (nome, indirizzo) values ('Sibyl Girdwood', '784 Schmedeman Park');
insert into cliente (nome, indirizzo) values ('Caresa Withringten', '94675 Bayside Terrace');
insert into cliente (nome, indirizzo) values ('Jacinta Yandle', '2615 Warbler Street');
insert into cliente (nome, indirizzo) values ('Marylou Baughn', '33 Helena Street');
insert into cliente (nome, indirizzo) values ('Lynnelle Flippen', '83 Stoughton Pass');
insert into cliente (nome, indirizzo) values ('Danette Ibel', '103 Norway Maple Drive');
insert into cliente (nome, indirizzo) values ('Mechelle Pithcock', '92 Susan Place');
insert into cliente (nome, indirizzo) values ('Anabella Budget', '8830 Golden Leaf Street');
insert into cliente (nome, indirizzo) values ('Rene Doncom', '54891 Pawling Way');
insert into cliente (nome, indirizzo) values ('Drusilla Orrey', '587 Kingsford Court');
insert into cliente (nome, indirizzo) values ('Carrissa Sextone', '9 Bluejay Place');
insert into cliente (nome, indirizzo) values ('Bing Skayman', '78 Melrose Alley');
insert into cliente (nome, indirizzo) values ('Laughton Green', '6124 Declaration Center');
insert into cliente (nome, indirizzo) values ('Lanni Cullinane', '7 Grover Street');
insert into cliente (nome, indirizzo) values ('Moll Slimme', '80 Rusk Center');
insert into cliente (nome, indirizzo) values ('Daisey Hanton', '4843 Boyd Hill');
insert into cliente (nome, indirizzo) values ('Audy Ygoe', '3 Mesta Place');
insert into cliente (nome, indirizzo) values ('Chaddy Tansley', '2 School Lane');
insert into cliente (nome, indirizzo) values ('Kenn Theodore', '00 New Castle Way');
insert into cliente (nome, indirizzo) values ('Lidia Evreux', '440 Sundown Pass');
insert into cliente (nome, indirizzo) values ('Mychal Lethieulier', '2812 Corscot Way');
insert into cliente (nome, indirizzo) values ('Blake Howsin', '709 Park Meadow Crossing');
insert into cliente (nome, indirizzo) values ('Boniface Daens', '52568 South Crossing');
insert into cliente (nome, indirizzo) values ('Sigfried Collumbell', '80803 Chive Street');
insert into cliente (nome, indirizzo) values ('Peder Cockburn', '6 Darwin Street');
insert into cliente (nome, indirizzo) values ('Boycie Dusting', '6 Center Way');
insert into cliente (nome, indirizzo) values ('Rosanne Corke', '63 Elmside Park');
insert into cliente (nome, indirizzo) values ('Cherye Cantopher', '54206 Artisan Drive');
insert into cliente (nome, indirizzo) values ('Christye Redihalgh', '2 Almo Hill');
insert into cliente (nome, indirizzo) values ('Olag McConway', '4 Paget Avenue');
insert into cliente (nome, indirizzo) values ('Ricard Digges', '42 Blue Bill Park Point');
insert into cliente (nome, indirizzo) values ('Brynne Marshall', '27713 Memorial Court');
insert into cliente (nome, indirizzo) values ('Cynde Janeway', '4 Cardinal Road');
insert into cliente (nome, indirizzo) values ('Massimiliano Varlow', '022 Raven Park');
insert into cliente (nome, indirizzo) values ('Nani Kirkbright', '1 Sundown Drive');
insert into cliente (nome, indirizzo) values ('Hilary Denholm', '241 Roth Way');
insert into cliente (nome, indirizzo) values ('Jackqueline Ledram', '3517 Alpine Way');
insert into cliente (nome, indirizzo) values ('Nettie Voysey', '644 Washington Park');
insert into cliente (nome, indirizzo) values ('Estrellita Olivera', '104 Michigan Road');
insert into cliente (nome, indirizzo) values ('Netti Couldwell', '61276 Randy Park');
insert into cliente (nome, indirizzo) values ('Velvet Alpes', '91 Summit Junction');
insert into cliente (nome, indirizzo) values ('Rosabel Longwood', '81337 Burning Wood Court');
insert into cliente (nome, indirizzo) values ('Amil Sterman', '7202 West Avenue');
insert into cliente (nome, indirizzo) values ('Althea Cossans', '78547 Cascade Court');
insert into cliente (nome, indirizzo) values ('Gleda McAvaddy', '1 Mccormick Junction');
insert into cliente (nome, indirizzo) values ('Jaymee Asbrey', '56682 Graedel Crossing');
insert into cliente (nome, indirizzo) values ('Devi Ricarde', '81878 Dwight Center');
insert into cliente (nome, indirizzo) values ('Raychel Petri', '13 Twin Pines Junction');
insert into cliente (nome, indirizzo) values ('Aloysius Claibourn', '9060 Fremont Way');
insert into cliente (nome, indirizzo) values ('Matias Rowan', '25 Westport Lane');
insert into cliente (nome, indirizzo) values ('Gawen Beadnell', '299 Banding Drive');
insert into cliente (nome, indirizzo) values ('Clarance Gayther', '42322 Dapin Place');
insert into cliente (nome, indirizzo) values ('Mareah Rowell', '10734 Miller Way');
insert into cliente (nome, indirizzo) values ('Huntley Howood', '582 Helena Circle');
insert into cliente (nome, indirizzo) values ('Tucker Grinnell', '9 Sloan Crossing');
insert into cliente (nome, indirizzo) values ('Modesty Menis', '34 Spaight Lane');
insert into cliente (nome, indirizzo) values ('Robbin Keatch', '1 Bellgrove Lane');
insert into cliente (nome, indirizzo) values ('Wilt Janczewski', '7 Havey Drive');
insert into cliente (nome, indirizzo) values ('Hirsch Echalie', '50436 Iowa Way');
insert into cliente (nome, indirizzo) values ('Neal Britee', '24 Schmedeman Terrace');
insert into cliente (nome, indirizzo) values ('Jerry Nevet', '11728 Hermina Street');
insert into cliente (nome, indirizzo) values ('Whitman Dikles', '6 Beilfuss Parkway');
insert into cliente (nome, indirizzo) values ('Joete MacDiarmond', '052 Thompson Way');
insert into cliente (nome, indirizzo) values ('Lanie Darkott', '831 High Crossing Way');
insert into cliente (nome, indirizzo) values ('Sidnee Soden', '59 Scoville Circle');
insert into cliente (nome, indirizzo) values ('Crawford Hefferon', '0 Rockefeller Parkway');
insert into cliente (nome, indirizzo) values ('Geoffry Fitzsimons', '49475 Anniversary Pass');
insert into cliente (nome, indirizzo) values ('Mildred Towriss', '07 Reindahl Street');
insert into cliente (nome, indirizzo) values ('Jobina Caton', '88032 Dahle Terrace');
insert into cliente (nome, indirizzo) values ('Bo Jaggi', '8 Grasskamp Street');
insert into cliente (nome, indirizzo) values ('Danila Dengate', '2 Waywood Crossing');
insert into cliente (nome, indirizzo) values ('Harriet De la Barre', '39521 Loftsgordon Road');
insert into cliente (nome, indirizzo) values ('Lilas Bernetti', '212 Hermina Way');
insert into cliente (nome, indirizzo) values ('Jeanette Philson', '4556 Larry Crossing');
insert into cliente (nome, indirizzo) values ('Ethan Julien', '26944 Shelley Road');
insert into cliente (nome, indirizzo) values ('Waylin Pinchon', '5 Roxbury Road');
insert into cliente (nome, indirizzo) values ('Willette Grave', '9271 Summerview Way');
insert into cliente (nome, indirizzo) values ('Sibel Goldster', '9 Boyd Place');
insert into cliente (nome, indirizzo) values ('Xaviera Pfeuffer', '744 Mockingbird Alley');
insert into cliente (nome, indirizzo) values ('Neill Milton', '1 Meadow Vale Place');
insert into cliente (nome, indirizzo) values ('Curt Matovic', '09 Magdeline Trail');
insert into cliente (nome, indirizzo) values ('Nikolaos Hirsch', '0945 Darwin Trail');
insert into cliente (nome, indirizzo) values ('Rickie Ambresin', '626 Grover Pass');
insert into cliente (nome, indirizzo) values ('Ferdinand Khan', '72064 Hudson Center');
insert into cliente (nome, indirizzo) values ('Elmo Kibbye', '4953 Gulseth Hill');
insert into cliente (nome, indirizzo) values ('Chen Jennaway', '720 Northland Center');
insert into cliente (nome, indirizzo) values ('Mic Kuhnke', '4 Magdeline Trail');
insert into cliente (nome, indirizzo) values ('Lance Hutchins', '8638 Stephen Center');
insert into cliente (nome, indirizzo) values ('D''arcy Brehaut', '2719 Lake View Drive');
insert into cliente (nome, indirizzo) values ('Eziechiele Aitken', '13493 Village Center');
insert into cliente (nome, indirizzo) values ('Marlow Thornewell', '066 Elmside Point');
insert into cliente (nome, indirizzo) values ('Clare Frontczak', '5 Corben Plaza');
insert into cliente (nome, indirizzo) values ('Roscoe Cribbott', '63995 Bluejay Hill');
insert into cliente (nome, indirizzo) values ('Dawn Jinkin', '4 Welch Alley');
insert into cliente (nome, indirizzo) values ('Stepha Grisard', '00462 Fieldstone Road');
insert into cliente (nome, indirizzo) values ('Donny McErlaine', '8845 Ludington Park');
insert into cliente (nome, indirizzo) values ('Clarisse Roskams', '47850 Springview Point');
insert into cliente (nome, indirizzo) values ('Paten McClay', '3 Tony Way');
insert into cliente (nome, indirizzo) values ('Carree Segoe', '07 Elka Center');
insert into cliente (nome, indirizzo) values ('Stanton Huddlestone', '4056 High Crossing Pass');
insert into cliente (nome, indirizzo) values ('Amabel Galley', '0272 Florence Drive');
insert into cliente (nome, indirizzo) values ('Tammy Kivits', '3512 Fremont Circle');
insert into cliente (nome, indirizzo) values ('Vikky Maudlin', '97 Monument Parkway');
insert into cliente (nome, indirizzo) values ('Wyndham Velden', '784 Oriole Crossing');
insert into cliente (nome, indirizzo) values ('Saxe Runnicles', '8 Bartillon Place');
insert into cliente (nome, indirizzo) values ('Margery Marousek', '6135 North Drive');
insert into cliente (nome, indirizzo) values ('Guenna Newarte', '92 Amoth Lane');
insert into cliente (nome, indirizzo) values ('Reggie Schust', '21 Gina Street');
insert into cliente (nome, indirizzo) values ('Berty Oglethorpe', '0 Loomis Point');
insert into cliente (nome, indirizzo) values ('Meade Gadman', '0 Northland Crossing');
insert into cliente (nome, indirizzo) values ('Dolley Cutten', '417 Sunfield Crossing');
insert into cliente (nome, indirizzo) values ('Iain Livard', '62742 Drewry Hill');
insert into cliente (nome, indirizzo) values ('Gallagher Flattman', '7 Dwight Crossing');
insert into cliente (nome, indirizzo) values ('Donia Harmer', '97 Farmco Circle');
insert into cliente (nome, indirizzo) values ('Marthe Plenderleith', '194 Reindahl Crossing');
insert into cliente (nome, indirizzo) values ('Carol Delooze', '4386 Nelson Lane');
insert into cliente (nome, indirizzo) values ('Palmer Bielefeld', '92772 Westport Road');
insert into cliente (nome, indirizzo) values ('Melesa Klimt', '79 Oak Valley Plaza');
insert into cliente (nome, indirizzo) values ('Milli Pettendrich', '2 Helena Hill');
insert into cliente (nome, indirizzo) values ('Kathryne Staddon', '4255 Bowman Point');
insert into cliente (nome, indirizzo) values ('Vilma Abrashkin', '276 Buell Way');
insert into cliente (nome, indirizzo) values ('Tim Boothby', '1112 Merry Parkway');
insert into cliente (nome, indirizzo) values ('Justinn Kemshell', '22797 Bluejay Parkway');
insert into cliente (nome, indirizzo) values ('Lodovico Fedorchenko', '90 Southridge Drive');
insert into cliente (nome, indirizzo) values ('Boote Moth', '62 Hallows Point');
insert into cliente (nome, indirizzo) values ('Phillis Pie', '5 Ramsey Street');
insert into cliente (nome, indirizzo) values ('Minna Iglesiaz', '165 Hooker Crossing');
insert into cliente (nome, indirizzo) values ('Alfons Malia', '41 Green Ridge Court');
insert into cliente (nome, indirizzo) values ('Nanete MacDonough', '52135 Acker Park');
insert into cliente (nome, indirizzo) values ('Jeremias Klimas', '9 Parkside Way');
insert into cliente (nome, indirizzo) values ('Tymothy Lindenblatt', '3337 Logan Terrace');
insert into cliente (nome, indirizzo) values ('Tedmund Walmsley', '85122 Clarendon Terrace');
insert into cliente (nome, indirizzo) values ('Tracie Skipp', '3 Cambridge Lane');
insert into cliente (nome, indirizzo) values ('Ibbie Winear', '42485 Welch Point');
insert into cliente (nome, indirizzo) values ('Arturo Whild', '16 Jenna Point');
insert into cliente (nome, indirizzo) values ('Jamey Roscamps', '7 Haas Terrace');
insert into cliente (nome, indirizzo) values ('Philippine Eakens', '754 Harper Plaza');
insert into cliente (nome, indirizzo) values ('Sabina Grimster', '8 Claremont Hill');
insert into cliente (nome, indirizzo) values ('Yorker Antos', '80023 Brentwood Pass');
insert into cliente (nome, indirizzo) values ('Mae Nash', '93388 Sloan Trail');
insert into cliente (nome, indirizzo) values ('Jdavie Horsted', '82746 Grover Place');
insert into cliente (nome, indirizzo) values ('Mella Moakes', '2193 Randy Road');
insert into cliente (nome, indirizzo) values ('Tadd Opdenorth', '2 Bayside Lane');
insert into cliente (nome, indirizzo) values ('Mord Jump', '9660 Eastwood Lane');
insert into cliente (nome, indirizzo) values ('Livvie O''Bruen', '3851 Sugar Lane');
insert into cliente (nome, indirizzo) values ('Ambrosi O''Cannon', '21 Ryan Circle');
insert into cliente (nome, indirizzo) values ('Kevina Casin', '667 Mcbride Terrace');
insert into cliente (nome, indirizzo) values ('Maia Lodwick', '660 Golf View Pass');
insert into cliente (nome, indirizzo) values ('Marline Patters', '2871 Lakewood Pass');
insert into cliente (nome, indirizzo) values ('Bernette Musico', '96778 Kings Junction');
insert into cliente (nome, indirizzo) values ('Mechelle Ebdon', '0798 Londonderry Crossing');
insert into cliente (nome, indirizzo) values ('Alexio Jefferies', '972 Kinsman Point');
insert into cliente (nome, indirizzo) values ('Duane Lightewood', '10974 Spaight Alley');
insert into cliente (nome, indirizzo) values ('Lonnie Kennicott', '330 Crownhardt Junction');
insert into cliente (nome, indirizzo) values ('Janot Delahunty', '33 Erie Way');
insert into cliente (nome, indirizzo) values ('Tiffy Chaffyn', '311 Maywood Hill');
insert into cliente (nome, indirizzo) values ('Sam Pendlebery', '9635 Bashford Street');
insert into cliente (nome, indirizzo) values ('Liane Luesley', '92 Linden Plaza');
insert into cliente (nome, indirizzo) values ('Trista Kilgrove', '601 Independence Way');
insert into cliente (nome, indirizzo) values ('Sky Marlen', '223 Lakewood Gardens Pass');
insert into cliente (nome, indirizzo) values ('Melvyn Calcutt', '66463 Vera Crossing');
insert into cliente (nome, indirizzo) values ('Raoul Sibille', '123 Butternut Hill');
insert into cliente (nome, indirizzo) values ('Lois Mettetal', '9624 5th Trail');
insert into cliente (nome, indirizzo) values ('Mitchel Pearsall', '7618 Elka Parkway');
insert into cliente (nome, indirizzo) values ('Glenda MacRinn', '28366 Manitowish Way');
insert into cliente (nome, indirizzo) values ('Estele Killimister', '345 Twin Pines Trail');
insert into cliente (nome, indirizzo) values ('Loralee Skells', '307 Clemons Drive');
insert into cliente (nome, indirizzo) values ('Lexie Campaigne', '39 Cascade Terrace');
insert into cliente (nome, indirizzo) values ('Beale Tenpenny', '9921 Barby Trail');
insert into cliente (nome, indirizzo) values ('Natty Sparkwell', '012 Hagan Lane');
insert into cliente (nome, indirizzo) values ('Bryanty Minichi', '162 Ruskin Terrace');
insert into cliente (nome, indirizzo) values ('Hunfredo Upchurch', '2 Aberg Avenue');
insert into cliente (nome, indirizzo) values ('Simonne Fort', '1421 Parkside Terrace');
insert into cliente (nome, indirizzo) values ('Callie Holah', '35 Valley Edge Alley');
insert into cliente (nome, indirizzo) values ('Ruthie Gravell', '07977 Haas Avenue');
insert into cliente (nome, indirizzo) values ('Lilla Humes', '9217 Arkansas Parkway');
insert into cliente (nome, indirizzo) values ('Honey Perazzo', '9255 Gerald Crossing');
insert into cliente (nome, indirizzo) values ('Mauricio Charity', '7104 New Castle Road');
insert into cliente (nome, indirizzo) values ('Radcliffe Scutter', '2505 Paget Center');
insert into cliente (nome, indirizzo) values ('Garth Hasser', '634 Norway Maple Pass');
insert into cliente (nome, indirizzo) values ('Annora Terrey', '078 Forster Terrace');
insert into cliente (nome, indirizzo) values ('Shawna Stang-Gjertsen', '7 Hallows Circle');
insert into cliente (nome, indirizzo) values ('Cristine McOwen', '861 Magdeline Terrace');
insert into cliente (nome, indirizzo) values ('Karie Bowbrick', '356 Russell Street');
insert into cliente (nome, indirizzo) values ('Phip Facer', '79881 Dakota Center');
insert into cliente (nome, indirizzo) values ('Briant Viles', '2 Prairieview Junction');
insert into cliente (nome, indirizzo) values ('Carroll Reader', '06671 Nelson Park');
insert into cliente (nome, indirizzo) values ('Marcellina de Lloyd', '745 Larry Street');
insert into cliente (nome, indirizzo) values ('Hashim Pfeffer', '97886 Oakridge Lane');
insert into cliente (nome, indirizzo) values ('Linzy Hendriks', '674 Parkside Park');
insert into cliente (nome, indirizzo) values ('Martelle Caffrey', '4520 Fulton Alley');
insert into cliente (nome, indirizzo) values ('Morgan Davio', '83 Jenna Center');
insert into cliente (nome, indirizzo) values ('Bucky Smithers', '8 Meadow Ridge Parkway');
insert into cliente (nome, indirizzo) values ('Della Hamsson', '25553 Scofield Lane');
insert into cliente (nome, indirizzo) values ('Patton Wolfenden', '28 Golf Course Pass');
insert into cliente (nome, indirizzo) values ('Bartlet Matches', '546 Dahle Alley');
insert into cliente (nome, indirizzo) values ('Nari Glanz', '5 Arrowood Center');
insert into cliente (nome, indirizzo) values ('Ambur Janusz', '8816 Stoughton Plaza');
insert into cliente (nome, indirizzo) values ('Trudie Aizikovitch', '07 Rockefeller Point');
insert into cliente (nome, indirizzo) values ('Meryl Serck', '68902 Heffernan Park');
insert into cliente (nome, indirizzo) values ('Garnet Biddles', '9 1st Road');
insert into cliente (nome, indirizzo) values ('Rudolf Covotto', '2171 Leroy Avenue');
insert into cliente (nome, indirizzo) values ('Raoul Lezemore', '3 Namekagon Street');
insert into cliente (nome, indirizzo) values ('Allen Cockshtt', '4 Nancy Plaza');
insert into cliente (nome, indirizzo) values ('Hallsy Stebbin', '06 Debra Park');
insert into cliente (nome, indirizzo) values ('Celinda Iacopo', '45033 Riverside Terrace');
insert into cliente (nome, indirizzo) values ('Trever Stroton', '1 Dayton Plaza');
insert into cliente (nome, indirizzo) values ('Vida Denerley', '96815 Talisman Junction');
insert into cliente (nome, indirizzo) values ('Martina Inchley', '31159 Fairfield Point');
insert into cliente (nome, indirizzo) values ('Zerk Vedstra', '959 Oak Way');
insert into cliente (nome, indirizzo) values ('Rosamond Ranyell', '08065 Brickson Park Street');
insert into cliente (nome, indirizzo) values ('Percival Leonards', '261 Havey Junction');
insert into cliente (nome, indirizzo) values ('Renaldo Shardlow', '4 Maple Circle');
insert into cliente (nome, indirizzo) values ('Griz Taffurelli', '0 Garrison Park');
insert into cliente (nome, indirizzo) values ('Mar Mathewson', '81 Randy Terrace');
insert into cliente (nome, indirizzo) values ('Guido Callen', '4 Corben Court');
insert into cliente (nome, indirizzo) values ('Hollis Gillitt', '6051 Beilfuss Point');
insert into cliente (nome, indirizzo) values ('Cayla Garling', '9 Troy Drive');
insert into cliente (nome, indirizzo) values ('Samaria Jacqueminet', '29369 Barby Alley');
insert into cliente (nome, indirizzo) values ('Bowie Cranmer', '14 Utah Park');
insert into cliente (nome, indirizzo) values ('Trevor Lenard', '63 Springs Plaza');
insert into cliente (nome, indirizzo) values ('Tess Briand', '3 Novick Park');
insert into cliente (nome, indirizzo) values ('Colver Grizard', '261 2nd Terrace');
insert into cliente (nome, indirizzo) values ('Gates Armistead', '5 Crowley Lane');
insert into cliente (nome, indirizzo) values ('Hermy Fance', '07 Rieder Drive');
insert into cliente (nome, indirizzo) values ('Leonardo Dryburgh', '664 Burrows Way');
insert into cliente (nome, indirizzo) values ('Hollyanne Yearn', '30 Harper Drive');
insert into cliente (nome, indirizzo) values ('Laurella Hedingham', '044 Elka Road');
insert into cliente (nome, indirizzo) values ('Bride Tschierasche', '74495 Burning Wood Avenue');
insert into cliente (nome, indirizzo) values ('Karoline Albertson', '85 Transport Circle');
insert into cliente (nome, indirizzo) values ('Jacky Rowlinson', '08818 Dexter Pass');
insert into cliente (nome, indirizzo) values ('Gaylene Pacquet', '64 Lake View Center');
insert into cliente (nome, indirizzo) values ('Chrotoem Delamaine', '70419 Lindbergh Terrace');
insert into cliente (nome, indirizzo) values ('Dru Bertomier', '5 Evergreen Pass');
insert into cliente (nome, indirizzo) values ('Blair Stucksbury', '8887 Anhalt Circle');
insert into cliente (nome, indirizzo) values ('Reinwald Di Filippo', '47 Blackbird Center');
insert into cliente (nome, indirizzo) values ('Teddie Brittin', '0 Almo Trail');
insert into cliente (nome, indirizzo) values ('Beckie Adshede', '96952 Trailsway Terrace');
insert into cliente (nome, indirizzo) values ('Obie Swanborrow', '38439 Boyd Drive');
insert into cliente (nome, indirizzo) values ('Free Scranedge', '42 Pepper Wood Avenue');
insert into cliente (nome, indirizzo) values ('Gamaliel Cunde', '853 Ronald Regan Place');
insert into cliente (nome, indirizzo) values ('Adi Curtiss', '790 Porter Park');
insert into cliente (nome, indirizzo) values ('Lauren Marcham', '0 Lotheville Place');
insert into cliente (nome, indirizzo) values ('Burk Steinham', '0743 Manley Terrace');
insert into cliente (nome, indirizzo) values ('Micheline Jozef', '0 Trailsway Place');
insert into cliente (nome, indirizzo) values ('Laurens De Blasiis', '777 Fuller Lane');
insert into cliente (nome, indirizzo) values ('Conny Albion', '8058 Pawling Junction');
insert into cliente (nome, indirizzo) values ('Rees Bonafacino', '1454 Magdeline Terrace');
insert into cliente (nome, indirizzo) values ('Thomasine Handman', '6098 Walton Avenue');
insert into cliente (nome, indirizzo) values ('Gert Kuschel', '060 Mcguire Lane');
insert into cliente (nome, indirizzo) values ('Mimi Hulke', '77376 Blue Bill Park Crossing');
insert into cliente (nome, indirizzo) values ('Marieann Heber', '5 Elka Point');
insert into cliente (nome, indirizzo) values ('Bernadene Cleiment', '1 Steensland Point');
insert into cliente (nome, indirizzo) values ('Georgena Gianneschi', '4447 Burrows Plaza');
insert into cliente (nome, indirizzo) values ('Cully Roony', '27 Londonderry Point');
insert into cliente (nome, indirizzo) values ('Winny Pollen', '3 Loomis Terrace');
insert into cliente (nome, indirizzo) values ('Carlo Risbie', '417 Center Drive');
insert into cliente (nome, indirizzo) values ('Hendrick Perse', '440 John Wall Plaza');
insert into cliente (nome, indirizzo) values ('Jeremiah Birds', '92827 Melody Alley');
insert into cliente (nome, indirizzo) values ('Teresita Espinal', '44 Westridge Place');
insert into cliente (nome, indirizzo) values ('Gerti Billings', '24503 Kedzie Road');
insert into cliente (nome, indirizzo) values ('Gerti Buttrick', '105 Armistice Street');
insert into cliente (nome, indirizzo) values ('Mathilda Fetherston', '85500 Pond Street');
insert into cliente (nome, indirizzo) values ('Hatty Aubrey', '21862 Loftsgordon Trail');
insert into cliente (nome, indirizzo) values ('Ethelyn Aronson', '84 American Pass');
insert into cliente (nome, indirizzo) values ('Tatiania Tremblot', '66161 Eastlawn Junction');
insert into cliente (nome, indirizzo) values ('Delia Marcinkowski', '81838 Forest Dale Park');
insert into cliente (nome, indirizzo) values ('Herrick Knottley', '4 3rd Junction');
insert into cliente (nome, indirizzo) values ('Broddy Argo', '170 Morrow Place');
insert into cliente (nome, indirizzo) values ('Jennie Simenon', '009 Lotheville Parkway');
insert into cliente (nome, indirizzo) values ('Pippo Wooles', '304 Pepper Wood Pass');
insert into cliente (nome, indirizzo) values ('Katerine Tarquinio', '234 Dunning Terrace');
insert into cliente (nome, indirizzo) values ('Halimeda Tregido', '34 Ilene Junction');
insert into cliente (nome, indirizzo) values ('Fredia Duferie', '1 Shasta Park');
insert into cliente (nome, indirizzo) values ('Shawn Casali', '1204 Talisman Way');
insert into cliente (nome, indirizzo) values ('Bear Averies', '8560 Shasta Court');
insert into cliente (nome, indirizzo) values ('Johannah Reaney', '4 Sauthoff Plaza');
insert into cliente (nome, indirizzo) values ('Rafael Widdowes', '32127 Forest Circle');
insert into cliente (nome, indirizzo) values ('Justine Armfirld', '7 Roxbury Place');
insert into cliente (nome, indirizzo) values ('Juliet Martynikhin', '6 La Follette Circle');
insert into cliente (nome, indirizzo) values ('Sheff Hann', '620 Bartelt Center');
insert into cliente (nome, indirizzo) values ('Blancha Deevey', '8 Walton Junction');
insert into cliente (nome, indirizzo) values ('Abra Makiver', '8 Milwaukee Avenue');
insert into cliente (nome, indirizzo) values ('Barbra Lardnar', '98 Aberg Street');
insert into cliente (nome, indirizzo) values ('Deane McMaster', '42 David Way');
insert into cliente (nome, indirizzo) values ('Davy Minthorpe', '60526 Longview Trail');
insert into cliente (nome, indirizzo) values ('Vale Dampney', '92169 Mitchell Way');
insert into cliente (nome, indirizzo) values ('Jonell Theze', '5828 Northridge Place');
insert into cliente (nome, indirizzo) values ('Katuscha Pinxton', '3687 Texas Street');
insert into cliente (nome, indirizzo) values ('Wain Bexley', '766 Anthes Way');
insert into cliente (nome, indirizzo) values ('Tab Roalfe', '94045 Victoria Street');
insert into cliente (nome, indirizzo) values ('Pippy Duffus', '9 Brentwood Junction');
insert into cliente (nome, indirizzo) values ('Tremaine Christene', '26840 Ilene Center');
insert into cliente (nome, indirizzo) values ('Lilly Winspar', '41 Schlimgen Center');
insert into cliente (nome, indirizzo) values ('Bernardo Piel', '943 Longview Center');
insert into cliente (nome, indirizzo) values ('Alene MacEntee', '99912 Eliot Hill');
insert into cliente (nome, indirizzo) values ('Alena Antoszczyk', '038 Sommers Point');
insert into cliente (nome, indirizzo) values ('Merrili Eglington', '12 Northview Pass');
insert into cliente (nome, indirizzo) values ('Nikola Jepperson', '1 Dapin Circle');
insert into cliente (nome, indirizzo) values ('Page Struis', '54 Farwell Place');
insert into cliente (nome, indirizzo) values ('Ruggiero Kamienski', '2860 Summer Ridge Junction');
insert into cliente (nome, indirizzo) values ('Thedric Lambdin', '95 Orin Center');
insert into cliente (nome, indirizzo) values ('Nobie Simionato', '23172 Mosinee Alley');
insert into cliente (nome, indirizzo) values ('Adams Emanuel', '00415 Paget Point');
insert into cliente (nome, indirizzo) values ('Nanette Fairnie', '96 Steensland Drive');
insert into cliente (nome, indirizzo) values ('Nathanial Jakubovicz', '919 Gina Terrace');
insert into cliente (nome, indirizzo) values ('Chandler Brokenbrow', '24 Oakridge Drive');
insert into cliente (nome, indirizzo) values ('Ediva Romi', '01 Gulseth Lane');
insert into cliente (nome, indirizzo) values ('Ella Croxall', '700 International Lane');
insert into cliente (nome, indirizzo) values ('Ingmar McAnulty', '847 Truax Drive');
insert into cliente (nome, indirizzo) values ('Jamill Oldall', '62223 Summit Center');
insert into cliente (nome, indirizzo) values ('Olva Garthland', '8036 Pepper Wood Trail');
insert into cliente (nome, indirizzo) values ('Briny Camock', '28567 Chinook Circle');
insert into cliente (nome, indirizzo) values ('Hertha Beggio', '40931 Sloan Court');
insert into cliente (nome, indirizzo) values ('Sunshine de Savery', '84294 Carioca Plaza');
insert into cliente (nome, indirizzo) values ('Myrle Ketteman', '26603 East Parkway');
insert into cliente (nome, indirizzo) values ('Teodoro Berk', '90392 Bellgrove Alley');
insert into cliente (nome, indirizzo) values ('Boy Barrett', '5 Vermont Court');
insert into cliente (nome, indirizzo) values ('Hersh Merryweather', '33 La Follette Lane');
insert into cliente (nome, indirizzo) values ('Keefe Simkins', '5 Ohio Court');
insert into cliente (nome, indirizzo) values ('Kathleen Gisburne', '876 Crescent Oaks Crossing');
insert into cliente (nome, indirizzo) values ('Farrell Maingot', '24957 Kedzie Alley');
insert into cliente (nome, indirizzo) values ('Olive Mellor', '3 Buena Vista Place');
insert into cliente (nome, indirizzo) values ('Abe Linzey', '8 Stephen Street');
insert into cliente (nome, indirizzo) values ('Kessiah Wimpey', '55 Everett Avenue');
insert into cliente (nome, indirizzo) values ('Alfons Argrave', '19880 Sommers Crossing');
insert into cliente (nome, indirizzo) values ('Cristiano Willgrass', '6317 Commercial Court');
insert into cliente (nome, indirizzo) values ('Urbano Sloper', '424 Oriole Lane');
insert into cliente (nome, indirizzo) values ('Julianne Rummer', '802 Mandrake Junction');
insert into cliente (nome, indirizzo) values ('Katie Soloway', '1 Pond Point');
insert into cliente (nome, indirizzo) values ('Collette Filinkov', '5256 Loftsgordon Road');
insert into cliente (nome, indirizzo) values ('Adelina Abotson', '35 Delaware Pass');
insert into cliente (nome, indirizzo) values ('Dewey Carabet', '26192 Myrtle Alley');
insert into cliente (nome, indirizzo) values ('Luce Treker', '93741 Susan Crossing');
insert into cliente (nome, indirizzo) values ('Charlena Maleney', '463 Farmco Lane');
insert into cliente (nome, indirizzo) values ('Andee Whitehouse', '2408 Cascade Drive');
insert into cliente (nome, indirizzo) values ('Hyacinth Hargrave', '5 Monica Alley');
insert into cliente (nome, indirizzo) values ('Almire Burges', '8589 Sutteridge Place');
insert into cliente (nome, indirizzo) values ('Ameline Almond', '4225 6th Parkway');
insert into cliente (nome, indirizzo) values ('Bess Cratchley', '558 Summer Ridge Pass');
insert into cliente (nome, indirizzo) values ('Arvy Sutton', '535 Russell Circle');
insert into cliente (nome, indirizzo) values ('Bink Prendergast', '4 Mccormick Place');
insert into cliente (nome, indirizzo) values ('Pace Petkens', '7 Meadow Valley Road');
insert into cliente (nome, indirizzo) values ('Brina Chennells', '2512 Hansons Alley');
insert into cliente (nome, indirizzo) values ('Lissie Dandison', '06 Arkansas Point');
insert into cliente (nome, indirizzo) values ('Jimmy Richardsson', '8 Dahle Trail');
insert into cliente (nome, indirizzo) values ('Pearle Arnoldi', '20 Ridge Oak Avenue');
insert into cliente (nome, indirizzo) values ('Sibylla Dimock', '8 Surrey Terrace');
insert into cliente (nome, indirizzo) values ('Gaby Mechi', '8011 Havey Drive');
insert into cliente (nome, indirizzo) values ('Welby Jilkes', '65 Montana Hill');
insert into cliente (nome, indirizzo) values ('Buckie Golden of Ireland', '3 Vahlen Center');
insert into cliente (nome, indirizzo) values ('Emelyne Kimmitt', '3 Butterfield Point');
insert into cliente (nome, indirizzo) values ('Meghann Virgin', '7 Center Court');
insert into cliente (nome, indirizzo) values ('Tommi Paireman', '8462 Village Plaza');
insert into cliente (nome, indirizzo) values ('Kaja Piris', '84 High Crossing Trail');
insert into cliente (nome, indirizzo) values ('Velvet Loosmore', '64699 Daystar Way');
insert into cliente (nome, indirizzo) values ('Milzie Kewley', '71 Northridge Plaza');
insert into cliente (nome, indirizzo) values ('Say Jeynes', '54758 Tennessee Way');
insert into cliente (nome, indirizzo) values ('Bernardine Romeo', '4 Sunnyside Avenue');
insert into cliente (nome, indirizzo) values ('Dori Kausche', '6 Donald Plaza');
insert into cliente (nome, indirizzo) values ('Abby Maddrell', '9528 Valley Edge Point');
insert into cliente (nome, indirizzo) values ('Carly Von Gladbach', '0 Drewry Alley');
insert into cliente (nome, indirizzo) values ('Samaria Flippelli', '5 Erie Park');
insert into cliente (nome, indirizzo) values ('Dud Scade', '34 Delaware Road');
insert into cliente (nome, indirizzo) values ('Deanne Maciaszek', '22882 1st Lane');
insert into cliente (nome, indirizzo) values ('Zarah Jeffery', '49 Green Drive');
insert into cliente (nome, indirizzo) values ('Kailey Vidgen', '791 Veith Park');
insert into cliente (nome, indirizzo) values ('Jorge Pennycuick', '1 Canary Parkway');
insert into cliente (nome, indirizzo) values ('Even Leadley', '9 Gerald Trail');
insert into cliente (nome, indirizzo) values ('Forrester Dumbarton', '6 Kinsman Street');
insert into cliente (nome, indirizzo) values ('Albie Booth', '74370 Portage Parkway');
insert into cliente (nome, indirizzo) values ('Matelda Brassington', '60387 Comanche Trail');
insert into cliente (nome, indirizzo) values ('Rachael Freer', '66 Ilene Hill');
insert into cliente (nome, indirizzo) values ('Winnah Sadler', '34213 Maywood Place');
insert into cliente (nome, indirizzo) values ('Aloise Domerc', '51061 Novick Park');
insert into cliente (nome, indirizzo) values ('Erasmus Belsham', '838 Huxley Terrace');
insert into cliente (nome, indirizzo) values ('Ailina Mayoral', '923 Homewood Parkway');
insert into cliente (nome, indirizzo) values ('Tallou McGlaud', '0 Spenser Junction');
insert into cliente (nome, indirizzo) values ('Aubrey Senescall', '0443 Kipling Court');
insert into cliente (nome, indirizzo) values ('Urbain McIlwrath', '2 Michigan Terrace');
insert into cliente (nome, indirizzo) values ('Cinda Murr', '277 Green Lane');
insert into cliente (nome, indirizzo) values ('Barbie Brain', '23142 Main Drive');
insert into cliente (nome, indirizzo) values ('Carly Hexham', '5783 Coolidge Drive');
insert into cliente (nome, indirizzo) values ('Damien Handover', '169 Riverside Trail');
insert into cliente (nome, indirizzo) values ('Mahmoud Philpault', '31 Prentice Pass');
insert into cliente (nome, indirizzo) values ('Hallie Danett', '73495 Bartelt Junction');
insert into cliente (nome, indirizzo) values ('Saundra Simpkiss', '90080 Village Park');
insert into cliente (nome, indirizzo) values ('Nari Treadwell', '75 Fulton Alley');
insert into cliente (nome, indirizzo) values ('Flossy Douty', '544 Hoepker Drive');
insert into cliente (nome, indirizzo) values ('Fax Wardington', '49 Vahlen Way');
insert into cliente (nome, indirizzo) values ('Ulrica Bineham', '8 Killdeer Junction');
insert into cliente (nome, indirizzo) values ('Phelia Teaz', '76 Eastwood Parkway');
insert into cliente (nome, indirizzo) values ('Jerome Bisson', '6391 Bellgrove Plaza');
insert into cliente (nome, indirizzo) values ('Ryan Baggalley', '9 Michigan Crossing');
insert into cliente (nome, indirizzo) values ('Gwen Farndell', '93110 Ohio Place');
insert into cliente (nome, indirizzo) values ('Hercules Massard', '88965 Crownhardt Center');
insert into cliente (nome, indirizzo) values ('Irvine Danielkiewicz', '96 Fordem Terrace');
insert into cliente (nome, indirizzo) values ('Darline Djurevic', '5475 Victoria Plaza');
insert into cliente (nome, indirizzo) values ('Sherman Crookes', '68832 Monument Way');
insert into cliente (nome, indirizzo) values ('Dorolisa Izzett', '7926 Waxwing Terrace');
insert into cliente (nome, indirizzo) values ('Malinde Blumer', '47 Anthes Drive');
insert into cliente (nome, indirizzo) values ('Selena Betun', '95 Kedzie Park');
insert into cliente (nome, indirizzo) values ('Jerrilee Langstone', '07490 Warrior Point');
insert into cliente (nome, indirizzo) values ('Sonnie Sawney', '18132 Cascade Park');
insert into cliente (nome, indirizzo) values ('Maryanna Woodyer', '26462 Bayside Circle');
insert into cliente (nome, indirizzo) values ('Janaye Collman', '23 Warbler Alley');
insert into cliente (nome, indirizzo) values ('Tiler Wint', '02021 Grover Hill');
insert into cliente (nome, indirizzo) values ('Sergeant Cadle', '25795 Reindahl Circle');
insert into cliente (nome, indirizzo) values ('Rosalinde Matej', '31478 Milwaukee Parkway');
insert into cliente (nome, indirizzo) values ('Rawley Bentley', '2332 Steensland Court');
insert into cliente (nome, indirizzo) values ('Vilhelmina Poyner', '58 Kipling Circle');
insert into cliente (nome, indirizzo) values ('Corbet Lamburn', '07 Mosinee Road');
insert into cliente (nome, indirizzo) values ('Marissa Rentelll', '59 Rieder Circle');
insert into cliente (nome, indirizzo) values ('Kiah Crabtree', '73 Blackbird Terrace');
insert into cliente (nome, indirizzo) values ('Graehme Hourston', '59 Milwaukee Circle');
insert into cliente (nome, indirizzo) values ('Melody Janata', '4987 Green Ridge Center');
insert into cliente (nome, indirizzo) values ('Etti Prickett', '04593 Hanson Street');
insert into cliente (nome, indirizzo) values ('Jacquelin Loalday', '79 Aberg Crossing');
insert into cliente (nome, indirizzo) values ('Jenine Rodden', '362 Barnett Place');
insert into cliente (nome, indirizzo) values ('Curtis Kenealy', '7621 Novick Center');
insert into cliente (nome, indirizzo) values ('Ransom Emmitt', '9 Quincy Parkway');
insert into cliente (nome, indirizzo) values ('Piper Bourthoumieux', '66747 Granby Crossing');
insert into cliente (nome, indirizzo) values ('Raven Hambrook', '77 Lakewood Circle');
insert into cliente (nome, indirizzo) values ('Elliott Grigorio', '98526 Chive Park');
insert into cliente (nome, indirizzo) values ('Samuel Plitz', '766 Vidon Avenue');
insert into cliente (nome, indirizzo) values ('Karly Reiach', '410 Lerdahl Parkway');
insert into cliente (nome, indirizzo) values ('Ricki Ramstead', '915 Kinsman Trail');
insert into cliente (nome, indirizzo) values ('Kienan Chainey', '85 Schurz Junction');
insert into cliente (nome, indirizzo) values ('Mollee Mountcastle', '620 Morning Hill');
insert into cliente (nome, indirizzo) values ('Elvira Pallis', '64 Dennis Crossing');
insert into cliente (nome, indirizzo) values ('Kermy Oxterby', '76 Pond Avenue');
insert into cliente (nome, indirizzo) values ('Leonidas Bounde', '25793 Pine View Court');
insert into cliente (nome, indirizzo) values ('Anjanette Yegorovnin', '61 Russell Junction');
insert into cliente (nome, indirizzo) values ('Chane Diver', '930 Derek Point');
insert into cliente (nome, indirizzo) values ('Dorine Philipeau', '542 Mendota Lane');
insert into cliente (nome, indirizzo) values ('Rae Goldine', '1 Memorial Place');
insert into cliente (nome, indirizzo) values ('Alexandros Roels', '71596 Union Hill');
insert into cliente (nome, indirizzo) values ('Rick Largen', '41996 Spenser Center');
insert into cliente (nome, indirizzo) values ('Bondy Swarbrick', '45172 Maryland Circle');
insert into cliente (nome, indirizzo) values ('Gwenneth Toplis', '322 Marcy Pass');
insert into cliente (nome, indirizzo) values ('Roana Sagar', '9458 Delladonna Terrace');
insert into cliente (nome, indirizzo) values ('Desiri Sichardt', '4 Spaight Street');
insert into cliente (nome, indirizzo) values ('Margareta Matyja', '79434 Kingsford Pass');
insert into cliente (nome, indirizzo) values ('Kellyann Troubridge', '5475 Lerdahl Center');
insert into cliente (nome, indirizzo) values ('Marcia Hainey`', '16299 Pawling Crossing');
insert into cliente (nome, indirizzo) values ('Lefty Blance', '55737 Brentwood Circle');
insert into cliente (nome, indirizzo) values ('Koren Joseland', '424 Roxbury Plaza');
insert into cliente (nome, indirizzo) values ('Janeczka Sibylla', '71422 International Lane');
insert into cliente (nome, indirizzo) values ('Dacie Corrett', '9 Eastwood Park');
insert into cliente (nome, indirizzo) values ('Derick Agglio', '78 Lunder Crossing');
insert into cliente (nome, indirizzo) values ('Katya O''Regan', '9973 Hoepker Point');
insert into cliente (nome, indirizzo) values ('Shane Alldred', '82 Heffernan Pass');
insert into cliente (nome, indirizzo) values ('Bevan Newart', '5 Blaine Crossing');
insert into cliente (nome, indirizzo) values ('Ax McGenis', '8 Stone Corner Drive');
insert into cliente (nome, indirizzo) values ('Berny Chetham', '15 1st Terrace');
insert into cliente (nome, indirizzo) values ('Adrianna Hurndall', '6402 Pond Alley');
insert into cliente (nome, indirizzo) values ('Lyda Lavell', '5 Montana Hill');
insert into cliente (nome, indirizzo) values ('Kellina Madden', '2471 Bayside Road');
insert into cliente (nome, indirizzo) values ('Hans Ulyatt', '694 Jenna Crossing');
insert into cliente (nome, indirizzo) values ('Ruthe Tamburi', '2 Sherman Place');
insert into cliente (nome, indirizzo) values ('Scot Sand', '5 Riverside Center');
insert into cliente (nome, indirizzo) values ('Portia Alejandre', '802 Luster Terrace');
insert into cliente (nome, indirizzo) values ('Noelani Walsh', '82312 Dovetail Place');
insert into cliente (nome, indirizzo) values ('Margot Jenkin', '10 Schmedeman Avenue');
insert into cliente (nome, indirizzo) values ('Nikolas Blazhevich', '04 Sloan Circle');
insert into cliente (nome, indirizzo) values ('Magnum Alessandrucci', '98085 Holmberg Drive');
insert into cliente (nome, indirizzo) values ('Leela Garman', '419 Merchant Way');
insert into cliente (nome, indirizzo) values ('Joeann Longega', '62 Fordem Drive');
insert into cliente (nome, indirizzo) values ('Franny Borchardt', '55 Monterey Way');
insert into cliente (nome, indirizzo) values ('Jaye Tregona', '148 East Park');
insert into cliente (nome, indirizzo) values ('Hortense Ridgley', '22576 Lerdahl Court');
insert into cliente (nome, indirizzo) values ('Christian Barneveld', '30874 Mandrake Way');
insert into cliente (nome, indirizzo) values ('Josselyn January', '72744 Ridgeview Crossing');
insert into cliente (nome, indirizzo) values ('Charlie Davidzon', '2 Mcguire Pass');
insert into cliente (nome, indirizzo) values ('Tull Toulmin', '5 Norway Maple Crossing');
insert into cliente (nome, indirizzo) values ('Fowler Alexandrou', '97 Homewood Lane');
insert into cliente (nome, indirizzo) values ('Peirce Hutchason', '10 Mifflin Crossing');
insert into cliente (nome, indirizzo) values ('Michaella Lefley', '50198 Mallory Lane');
insert into cliente (nome, indirizzo) values ('Nowell Trevear', '99474 Derek Trail');
insert into cliente (nome, indirizzo) values ('Creighton Goneau', '02190 Manufacturers Place');
insert into cliente (nome, indirizzo) values ('Diane-marie Tow', '58 Mendota Parkway');
insert into cliente (nome, indirizzo) values ('Carlynne Pegg', '605 Meadow Valley Junction');
insert into cliente (nome, indirizzo) values ('Bradan Hearl', '7 Victoria Drive');
insert into cliente (nome, indirizzo) values ('Baldwin Tropman', '13613 Sunfield Circle');
insert into cliente (nome, indirizzo) values ('Kort Cottham', '0 Hanover Junction');
insert into cliente (nome, indirizzo) values ('Janeen Carlisle', '5814 Gina Road');
insert into cliente (nome, indirizzo) values ('Ailey Henrot', '57 David Crossing');
insert into cliente (nome, indirizzo) values ('Ambrose Husset', '53 Stone Corner Road');
insert into cliente (nome, indirizzo) values ('Mirabella Doig', '1682 Butternut Court');
insert into cliente (nome, indirizzo) values ('Muffin Paulich', '7166 Dayton Alley');
insert into cliente (nome, indirizzo) values ('Gothart Kenworthey', '9 Graceland Junction');
insert into cliente (nome, indirizzo) values ('Peyter Wattins', '23 Bartillon Parkway');
insert into cliente (nome, indirizzo) values ('Maurine Geeves', '0 Corry Center');
insert into cliente (nome, indirizzo) values ('Lillis Rintoul', '3 Division Center');
insert into cliente (nome, indirizzo) values ('Lydon Rawsen', '00527 Mayer Hill');
insert into cliente (nome, indirizzo) values ('Chiquita Totaro', '03027 Brentwood Plaza');
insert into cliente (nome, indirizzo) values ('Ingeberg Poone', '74 Magdeline Point');
insert into cliente (nome, indirizzo) values ('Mayne Haws', '9 Springs Circle');
insert into cliente (nome, indirizzo) values ('Mattheus Mousley', '96329 Hollow Ridge Crossing');
insert into cliente (nome, indirizzo) values ('Myrtice Mendel', '8492 Grayhawk Way');
insert into cliente (nome, indirizzo) values ('Ruthie Klug', '99903 Hovde Parkway');
insert into cliente (nome, indirizzo) values ('Claudio Humphrey', '54453 Kennedy Point');
insert into cliente (nome, indirizzo) values ('Adrian Reisk', '0897 Loftsgordon Crossing');
insert into cliente (nome, indirizzo) values ('Ardyce Dispencer', '1 Lakewood Junction');
insert into cliente (nome, indirizzo) values ('Willey Sinkings', '3632 4th Hill');
insert into cliente (nome, indirizzo) values ('Claudelle Matuszynski', '989 Aberg Point');
insert into cliente (nome, indirizzo) values ('Lenora Hawkeswood', '932 Mcguire Alley');
insert into cliente (nome, indirizzo) values ('Haze Pury', '6 Esch Plaza');
insert into cliente (nome, indirizzo) values ('Lea Sones', '6214 Larry Road');
insert into cliente (nome, indirizzo) values ('Grata Giercke', '9 Tomscot Lane');
insert into cliente (nome, indirizzo) values ('Devinne Ludye', '5 Merchant Court');
insert into cliente (nome, indirizzo) values ('Chrisse Allman', '80 Marcy Avenue');
insert into cliente (nome, indirizzo) values ('Loleta Guille', '2081 Transport Junction');
insert into cliente (nome, indirizzo) values ('Edd Bracher', '69590 Nelson Avenue');
insert into cliente (nome, indirizzo) values ('Chryste Dennington', '2345 Sachs Crossing');
insert into cliente (nome, indirizzo) values ('Magdalene Issac', '0 Loomis Plaza');
insert into cliente (nome, indirizzo) values ('Vikky Casarino', '30 Hazelcrest Crossing');
insert into cliente (nome, indirizzo) values ('Lion Spitaro', '7 Kipling Park');
insert into cliente (nome, indirizzo) values ('Sanson MacGorley', '2094 Mesta Circle');
insert into cliente (nome, indirizzo) values ('Cathi McKenney', '05412 Nobel Trail');
insert into cliente (nome, indirizzo) values ('Anthia Page', '64363 Dennis Terrace');
insert into cliente (nome, indirizzo) values ('Oralie Petrozzi', '77 Kipling Terrace');
insert into cliente (nome, indirizzo) values ('Findley Stannett', '33 Ludington Plaza');
insert into cliente (nome, indirizzo) values ('Fletch Sollis', '71 Hanover Hill');
insert into cliente (nome, indirizzo) values ('Kalie Lutman', '51 Riverside Road');
insert into cliente (nome, indirizzo) values ('Merl Lovelady', '624 Miller Terrace');
insert into cliente (nome, indirizzo) values ('Enid Fife', '45152 Bartelt Trail');
insert into cliente (nome, indirizzo) values ('Joli Baudts', '63463 Rusk Street');
insert into cliente (nome, indirizzo) values ('Alis Worling', '9203 Badeau Park');
insert into cliente (nome, indirizzo) values ('Jori Preece', '122 Lotheville Alley');
insert into cliente (nome, indirizzo) values ('Marguerite Teall', '23289 Merchant Court');
insert into cliente (nome, indirizzo) values ('Anderson Rimour', '796 Aberg Plaza');
insert into cliente (nome, indirizzo) values ('Ginnifer Eustanch', '7 Fremont Trail');
insert into cliente (nome, indirizzo) values ('Reynold Ekins', '6339 Texas Park');
insert into cliente (nome, indirizzo) values ('Davy Demageard', '61537 Starling Street');
insert into cliente (nome, indirizzo) values ('Eleonora Tongs', '6 Nancy Circle');
insert into cliente (nome, indirizzo) values ('Hobie Cribbins', '5688 Clarendon Lane');
insert into cliente (nome, indirizzo) values ('Ailsun Sowte', '640 Straubel Center');
insert into cliente (nome, indirizzo) values ('Lanie Chart', '81989 Artisan Alley');
insert into cliente (nome, indirizzo) values ('Barnaby Trevarthen', '8 Reinke Place');
insert into cliente (nome, indirizzo) values ('Lynde Hedges', '84 Clyde Gallagher Park');
insert into cliente (nome, indirizzo) values ('Tootsie Faich', '597 Burning Wood Place');
insert into cliente (nome, indirizzo) values ('Erskine Renish', '09031 Cordelia Junction');
insert into cliente (nome, indirizzo) values ('Juanita McGuinness', '3 Jana Alley');
insert into cliente (nome, indirizzo) values ('Johan Bartosek', '9041 Linden Parkway');
insert into cliente (nome, indirizzo) values ('Kingsley Biers', '85381 Sloan Center');
insert into cliente (nome, indirizzo) values ('Harri Demogeot', '9 Mendota Plaza');
insert into cliente (nome, indirizzo) values ('Lexy Birdwhistell', '8 Dexter Lane');
insert into cliente (nome, indirizzo) values ('Goran Gallahar', '61257 Twin Pines Place');
insert into cliente (nome, indirizzo) values ('Leonard Slocum', '17273 Messerschmidt Place');
insert into cliente (nome, indirizzo) values ('Kellen Bowller', '32 Golf Course Pass');
insert into cliente (nome, indirizzo) values ('Emanuele Breitling', '47 Fisk Lane');
insert into cliente (nome, indirizzo) values ('Alisha Loache', '431 High Crossing Circle');
insert into cliente (nome, indirizzo) values ('Rosette Dunsmuir', '9016 Eliot Street');
insert into cliente (nome, indirizzo) values ('Rolando Duckham', '83412 Katie Hill');
insert into cliente (nome, indirizzo) values ('Chery Blakeston', '48 Dottie Way');
insert into cliente (nome, indirizzo) values ('Tandy Schanke', '4 Grim Terrace');
insert into cliente (nome, indirizzo) values ('Angie Castagno', '3 Trailsway Park');
insert into cliente (nome, indirizzo) values ('Raul Lehrian', '5 Sutherland Drive');
insert into cliente (nome, indirizzo) values ('Jacqui Battin', '132 John Wall Street');
insert into cliente (nome, indirizzo) values ('Erastus Bus', '390 Golf Plaza');
insert into cliente (nome, indirizzo) values ('Dolph Coakley', '20 Pepper Wood Place');
insert into cliente (nome, indirizzo) values ('Arnoldo Covell', '643 Barby Place');
insert into cliente (nome, indirizzo) values ('Xavier Cainey', '7 Clarendon Street');
insert into cliente (nome, indirizzo) values ('Filberte Kielty', '102 Morrow Center');
insert into cliente (nome, indirizzo) values ('Emilie Paramor', '228 Warbler Plaza');
insert into cliente (nome, indirizzo) values ('Bourke Delacroux', '540 Basil Pass');
insert into cliente (nome, indirizzo) values ('Lauryn Hollingdale', '328 Coolidge Circle');
insert into cliente (nome, indirizzo) values ('Veronike Oldknow', '8 Blackbird Point');
insert into cliente (nome, indirizzo) values ('Valentine Samwell', '27 Shelley Park');
insert into cliente (nome, indirizzo) values ('Adolph Benaine', '1 Westridge Junction');
insert into cliente (nome, indirizzo) values ('Nonna Sauvan', '0084 Sachtjen Parkway');
insert into cliente (nome, indirizzo) values ('Drugi Keel', '0 Petterle Terrace');
insert into cliente (nome, indirizzo) values ('Win Broadberrie', '97 Lawn Street');
insert into cliente (nome, indirizzo) values ('Ansell Sloper', '8 Hanover Parkway');
insert into cliente (nome, indirizzo) values ('Trish Dring', '6 Kenwood Park');
insert into cliente (nome, indirizzo) values ('Meta Ivashechkin', '03931 Eagan Trail');
insert into cliente (nome, indirizzo) values ('Josephine Orrom', '890 Gulseth Way');
insert into cliente (nome, indirizzo) values ('Griff Kornel', '2 Glacier Hill Alley');
insert into cliente (nome, indirizzo) values ('Lexie Streeter', '8441 Dennis Court');
insert into cliente (nome, indirizzo) values ('Mable Furbank', '96 Melby Avenue');
insert into cliente (nome, indirizzo) values ('Jud Ashelford', '8 Bay Hill');
insert into cliente (nome, indirizzo) values ('Roda Ayerst', '368 Gateway Parkway');
insert into cliente (nome, indirizzo) values ('Glori Nibley', '6 Wayridge Place');
insert into cliente (nome, indirizzo) values ('Burlie Khristoforov', '16 Saint Paul Alley');
insert into cliente (nome, indirizzo) values ('Bay Ussher', '5 Debra Avenue');
insert into cliente (nome, indirizzo) values ('Madelene Tiffney', '0120 Hooker Lane');
insert into cliente (nome, indirizzo) values ('Audrey Paniman', '3516 Buhler Point');
insert into cliente (nome, indirizzo) values ('Candy Papa', '627 Mockingbird Road');
insert into cliente (nome, indirizzo) values ('Belicia Toombes', '4 Lien Point');
insert into cliente (nome, indirizzo) values ('Jeri Donaher', '7428 Melody Drive');
insert into cliente (nome, indirizzo) values ('Dora Nisot', '1801 Grim Place');
insert into cliente (nome, indirizzo) values ('Arliene Radleigh', '3 Badeau Plaza');
insert into cliente (nome, indirizzo) values ('Orrin Leedal', '45704 Dottie Court');
insert into cliente (nome, indirizzo) values ('Mandie Tagg', '0 Lotheville Lane');
insert into cliente (nome, indirizzo) values ('Quinlan Crowson', '5932 Waxwing Crossing');
insert into cliente (nome, indirizzo) values ('Sid Auchterlony', '3 Hoard Center');
insert into cliente (nome, indirizzo) values ('Lloyd Breed', '04 Paget Crossing');
insert into cliente (nome, indirizzo) values ('Edd Bolduc', '4 Golf Place');
insert into cliente (nome, indirizzo) values ('Marisa Fuzzard', '812 Graedel Plaza');
insert into cliente (nome, indirizzo) values ('Constancy Miliffe', '7735 Farragut Place');
insert into cliente (nome, indirizzo) values ('Sander Middleweek', '8 Jackson Parkway');
insert into cliente (nome, indirizzo) values ('Birgitta Stedell', '2335 Maple Terrace');
insert into cliente (nome, indirizzo) values ('Cloris Ferriby', '003 Thompson Hill');
insert into cliente (nome, indirizzo) values ('Flory Tukely', '51 Helena Drive');
insert into cliente (nome, indirizzo) values ('Maressa Biset', '207 Barby Plaza');
insert into cliente (nome, indirizzo) values ('Marilee Breffitt', '764 Towne Drive');
insert into cliente (nome, indirizzo) values ('Nissie Trillow', '49719 Nancy Alley');
insert into cliente (nome, indirizzo) values ('Kristofor Spalls', '181 Bonner Road');
insert into cliente (nome, indirizzo) values ('Berrie Peto', '0 Lakewood Circle');
insert into cliente (nome, indirizzo) values ('Angelika Kybird', '1 Clarendon Point');
insert into cliente (nome, indirizzo) values ('Torrence Gommery', '096 Hintze Road');
insert into cliente (nome, indirizzo) values ('Anestassia Beautyman', '343 Parkside Lane');
insert into cliente (nome, indirizzo) values ('Vickie Harte', '9625 Pine View Terrace');
insert into cliente (nome, indirizzo) values ('Alphonso McKinnell', '94 Utah Lane');
insert into cliente (nome, indirizzo) values ('Willi Jodrelle', '1 Mifflin Alley');
insert into cliente (nome, indirizzo) values ('Sapphire Coyte', '23 Shoshone Hill');
insert into cliente (nome, indirizzo) values ('Paddy Meron', '599 6th Trail');
insert into cliente (nome, indirizzo) values ('Domenic Chimes', '444 North Terrace');
insert into cliente (nome, indirizzo) values ('Olivero Dellenty', '76 Brentwood Junction');
insert into cliente (nome, indirizzo) values ('Ibbie Arthan', '8790 Chive Circle');
insert into cliente (nome, indirizzo) values ('Catina Illem', '22 Columbus Alley');
insert into cliente (nome, indirizzo) values ('Dore Stoneley', '19 Armistice Pass');
insert into cliente (nome, indirizzo) values ('Denice Bethel', '4139 Fordem Avenue');
insert into cliente (nome, indirizzo) values ('Arni Scryne', '9 Forest Run Way');
insert into cliente (nome, indirizzo) values ('Vittoria Tweedy', '36 3rd Parkway');
insert into cliente (nome, indirizzo) values ('Arluene MacKenzie', '0336 Merrick Place');
insert into cliente (nome, indirizzo) values ('Joseph Kimbling', '6 Arapahoe Pass');
insert into cliente (nome, indirizzo) values ('Gabbi Diviny', '85010 Oak Valley Trail');
insert into cliente (nome, indirizzo) values ('Peadar Stichel', '68562 Merchant Place');
insert into cliente (nome, indirizzo) values ('Mathe Euler', '82 Banding Crossing');
insert into cliente (nome, indirizzo) values ('Kayley Chadwin', '15833 Trailsway Circle');
insert into cliente (nome, indirizzo) values ('Bonny Vorley', '852 Dixon Parkway');
insert into cliente (nome, indirizzo) values ('Rhetta Elton', '157 Manley Alley');
insert into cliente (nome, indirizzo) values ('Iosep Littlepage', '2 Florence Crossing');
insert into cliente (nome, indirizzo) values ('Avictor Kirtlan', '03705 Bowman Park');
insert into cliente (nome, indirizzo) values ('Fidole Maggorini', '54 Randy Avenue');
insert into cliente (nome, indirizzo) values ('Myrtice Weal', '3 Lake View Street');
insert into cliente (nome, indirizzo) values ('Noby Friskey', '4 Havey Pass');
insert into cliente (nome, indirizzo) values ('Nathanial Sodor', '3 Vernon Drive');
insert into cliente (nome, indirizzo) values ('Bondon McNaughton', '98782 Schurz Road');
insert into cliente (nome, indirizzo) values ('Davina Manueau', '33171 Cascade Way');
insert into cliente (nome, indirizzo) values ('El Baldrey', '43 Jay Court');
insert into cliente (nome, indirizzo) values ('Julita Kryzhov', '3 7th Place');
insert into cliente (nome, indirizzo) values ('Waly Rosenblatt', '428 Morningstar Court');
insert into cliente (nome, indirizzo) values ('Saleem Pallesen', '748 Kropf Point');
insert into cliente (nome, indirizzo) values ('Nissie Filson', '878 Clyde Gallagher Pass');
insert into cliente (nome, indirizzo) values ('Jeffrey Lobley', '28 Packers Junction');
insert into cliente (nome, indirizzo) values ('Siusan Raspison', '59 Norway Maple Terrace');
insert into cliente (nome, indirizzo) values ('Ardith Shaddick', '057 Dapin Parkway');
insert into cliente (nome, indirizzo) values ('Pauly Bernat', '1053 Rowland Court');
insert into cliente (nome, indirizzo) values ('Sterne Ketteridge', '9742 Oxford Plaza');
insert into cliente (nome, indirizzo) values ('Paulette Mateescu', '2 Arrowood Trail');
insert into cliente (nome, indirizzo) values ('Tibold Sellor', '377 Golden Leaf Court');
insert into cliente (nome, indirizzo) values ('Adamo Findlater', '1324 Armistice Circle');
insert into cliente (nome, indirizzo) values ('Granville Pull', '428 Lunder Alley');
insert into cliente (nome, indirizzo) values ('Tomkin Krabbe', '21 Schurz Drive');
insert into cliente (nome, indirizzo) values ('Hally Gregr', '09 Donald Park');
insert into cliente (nome, indirizzo) values ('Nefen Baudone', '7 Goodland Trail');
insert into cliente (nome, indirizzo) values ('Alec Estcot', '98288 Kenwood Junction');
insert into cliente (nome, indirizzo) values ('Eran Fulk', '93774 Darwin Point');
insert into cliente (nome, indirizzo) values ('Sioux Jollands', '94613 Barnett Center');
insert into cliente (nome, indirizzo) values ('Bent Hindrick', '23286 Darwin Place');
insert into cliente (nome, indirizzo) values ('Minette Cray', '96 Meadow Ridge Point');
insert into cliente (nome, indirizzo) values ('Diann McGinn', '939 Waywood Junction');
insert into cliente (nome, indirizzo) values ('Nannie Nicolls', '61618 Ruskin Circle');
insert into cliente (nome, indirizzo) values ('Borg Artois', '49535 Vera Pass');
insert into cliente (nome, indirizzo) values ('Jeremie Simnell', '9 Mallard Court');
insert into cliente (nome, indirizzo) values ('Gavra Easey', '2398 Center Street');
insert into cliente (nome, indirizzo) values ('North Maingot', '57 Ludington Court');
insert into cliente (nome, indirizzo) values ('Danya Parbrook', '6 Scoville Place');
insert into cliente (nome, indirizzo) values ('Ernesto Lismer', '67 Melody Crossing');
insert into cliente (nome, indirizzo) values ('Gearard Morrel', '79 Hollow Ridge Parkway');
insert into cliente (nome, indirizzo) values ('Logan Anelay', '81 Fremont Lane');
insert into cliente (nome, indirizzo) values ('Hanni Rickeard', '788 Esch Trail');
insert into cliente (nome, indirizzo) values ('Joshua Shepcutt', '4 Quincy Drive');
insert into cliente (nome, indirizzo) values ('Guido Charkham', '77 Welch Place');
insert into cliente (nome, indirizzo) values ('Justin Chess', '97322 Jay Street');
insert into cliente (nome, indirizzo) values ('Virgil Van Driel', '8 Canary Trail');
insert into cliente (nome, indirizzo) values ('Lexis Soughton', '8277 Lunder Crossing');
insert into cliente (nome, indirizzo) values ('Lisbeth Tolland', '2195 Schiller Place');
insert into cliente (nome, indirizzo) values ('Mela Grigorini', '94 Chive Alley');
insert into cliente (nome, indirizzo) values ('Alphonse Rush', '4229 Manley Place');
insert into cliente (nome, indirizzo) values ('Merrili Matushevich', '86945 Darwin Crossing');
insert into cliente (nome, indirizzo) values ('Dottie Gelletly', '57071 Pearson Drive');
insert into cliente (nome, indirizzo) values ('Schuyler Gallacher', '14857 Kipling Parkway');
insert into cliente (nome, indirizzo) values ('Benjamin Peyton', '3 Erie Place');
insert into cliente (nome, indirizzo) values ('Jami Dionsetto', '8 Bashford Hill');
insert into cliente (nome, indirizzo) values ('Elvira Baistow', '645 Ridge Oak Trail');
insert into cliente (nome, indirizzo) values ('Lira Joubert', '864 Welch Center');
insert into cliente (nome, indirizzo) values ('Evangeline Garard', '340 Hazelcrest Hill');
insert into cliente (nome, indirizzo) values ('Timotheus Laval', '367 Delaware Circle');
insert into cliente (nome, indirizzo) values ('Olav Strafen', '4 Saint Paul Park');
insert into cliente (nome, indirizzo) values ('Denny Van der Linde', '93736 Carioca Crossing');
insert into cliente (nome, indirizzo) values ('Anica Veale', '88926 Village Green Crossing');
insert into cliente (nome, indirizzo) values ('Mureil Quilleash', '1 Springview Crossing');
insert into cliente (nome, indirizzo) values ('Keefer Prugel', '8 Corben Pass');
insert into cliente (nome, indirizzo) values ('Loise Hubber', '09 Del Sol Center');
insert into cliente (nome, indirizzo) values ('Hermy Basford', '2980 Chive Parkway');
insert into cliente (nome, indirizzo) values ('Fifi Worton', '2924 Sommers Road');
insert into cliente (nome, indirizzo) values ('Kendre Disbury', '8 Chinook Court');
