insert into fornitore (nome, indirizzo) values ('Barrows-Wuckert', '31111 Schurz Junction');
insert into fornitore (nome, indirizzo) values ('Hettinger-Nicolas', '6472 Dorton Parkway');
insert into fornitore (nome, indirizzo) values ('Marvin and Sons', '563 Dixon Street');
insert into fornitore (nome, indirizzo) values ('Bogan-Kshlerin', '1703 Anhalt Crossing');
insert into fornitore (nome, indirizzo) values ('Marquardt-Zboncak', '5304 Hayes Way');
insert into fornitore (nome, indirizzo) values ('Cummings Group', '1214 Mitchell Parkway');
insert into fornitore (nome, indirizzo) values ('Dare-Hessel', '6447 Nevada Lane');
insert into fornitore (nome, indirizzo) values ('Nicolas, Bayer and Schaden', '8 Oak Valley Junction');
insert into fornitore (nome, indirizzo) values ('Von LLC', '80778 Mallard Center');
insert into fornitore (nome, indirizzo) values ('Hansen and Sons', '5962 South Hill');
insert into fornitore (nome, indirizzo) values ('Walsh Group', '2749 Little Fleur Circle');
insert into fornitore (nome, indirizzo) values ('Mills, Ratke and Grant', '3 Erie Park');
insert into fornitore (nome, indirizzo) values ('Keebler Inc', '77703 Swallow Way');
insert into fornitore (nome, indirizzo) values ('Williamson and Sons', '131 Loftsgordon Hill');
insert into fornitore (nome, indirizzo) values ('Sauer and Sons', '61 Nelson Pass');
insert into fornitore (nome, indirizzo) values ('Leuschke-Reichert', '5 Surrey Center');
insert into fornitore (nome, indirizzo) values ('Lockman-Legros', '6473 Artisan Place');
insert into fornitore (nome, indirizzo) values ('Mraz and Sons', '33 Arapahoe Parkway');
insert into fornitore (nome, indirizzo) values ('Ruecker Inc', '8606 Esker Parkway');
insert into fornitore (nome, indirizzo) values ('Zboncak, Farrell and Wolf', '54318 Melody Lane');
insert into fornitore (nome, indirizzo) values ('Weissnat LLC', '62 Esker Circle');
insert into fornitore (nome, indirizzo) values ('Kassulke Group', '936 Ramsey Circle');
insert into fornitore (nome, indirizzo) values ('Carroll-Gerlach', '2505 High Crossing Plaza');
insert into fornitore (nome, indirizzo) values ('Dach-Bayer', '5 Acker Crossing');
insert into fornitore (nome, indirizzo) values ('Orn-Hermann', '6742 Westridge Trail');
insert into fornitore (nome, indirizzo) values ('Collier, Roob and Gerlach', '205 Talmadge Plaza');
insert into fornitore (nome, indirizzo) values ('Kutch-VonRueden', '77227 Darwin Crossing');
insert into fornitore (nome, indirizzo) values ('Hermiston, Block and Hudson', '0850 Fisk Court');
insert into fornitore (nome, indirizzo) values ('Braun Group', '2939 Darwin Point');
insert into fornitore (nome, indirizzo) values ('O''Reilly, Wiza and Bradtke', '54 Village Pass');
insert into fornitore (nome, indirizzo) values ('Lueilwitz, Spencer and O''Reilly', '469 Summerview Alley');
insert into fornitore (nome, indirizzo) values ('Wintheiser-Harber', '8985 Little Fleur Pass');
insert into fornitore (nome, indirizzo) values ('White Inc', '55029 Dottie Point');
insert into fornitore (nome, indirizzo) values ('Torp, Spencer and Prosacco', '2993 Merchant Hill');
insert into fornitore (nome, indirizzo) values ('Rau Group', '56 Commercial Hill');
insert into fornitore (nome, indirizzo) values ('Lowe-Ward', '2 Prentice Road');
insert into fornitore (nome, indirizzo) values ('Legros and Sons', '22 Maple Wood Center');
insert into fornitore (nome, indirizzo) values ('Little, Cummings and Kozey', '85 Dwight Park');
insert into fornitore (nome, indirizzo) values ('Bahringer, Feil and Heaney', '36 Portage Alley');
insert into fornitore (nome, indirizzo) values ('Leffler Group', '24 Sundown Park');
insert into fornitore (nome, indirizzo) values ('Barton LLC', '784 Summer Ridge Avenue');
insert into fornitore (nome, indirizzo) values ('Hauck-O''Conner', '5469 Blaine Terrace');
insert into fornitore (nome, indirizzo) values ('Hane, Bernhard and Hettinger', '30 Sycamore Hill');
insert into fornitore (nome, indirizzo) values ('Pfeffer Group', '117 Clemons Court');
insert into fornitore (nome, indirizzo) values ('Medhurst, Streich and Schiller', '9734 Weeping Birch Circle');
insert into fornitore (nome, indirizzo) values ('Williamson-Walsh', '318 Center Junction');
insert into fornitore (nome, indirizzo) values ('Hayes and Sons', '063 Mayer Way');
insert into fornitore (nome, indirizzo) values ('Renner Group', '359 4th Terrace');
insert into fornitore (nome, indirizzo) values ('Huels Group', '40469 Fair Oaks Park');
insert into fornitore (nome, indirizzo) values ('Bayer LLC', '411 Bluejay Hill');
