insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (1, 79.79, 'Chocolate Bar - Oh Henry', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (2, 73.17, 'Chocolate - Semi Sweet', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (3, 28.62, 'Lambcasing', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (4, 96.95, 'Lettuce - Treviso', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (5, 96.13, 'Wine - Conde De Valdemar', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (6, 31.24, 'Flour - Strong Pizza', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (7, 5.87, 'Cheese Cloth', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (8, 64.61, 'Fudge - Chocolate Fudge', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (9, 46.78, 'Juice - Orange, 341 Ml', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (10, 3.41, 'Bagel - Everything Presliced', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (11, 51.43, 'Red Pepper Paste', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (12, 19.44, 'Ice - Clear, 300 Lb For Carving', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (13, 23.69, 'Pepper - Scotch Bonnet', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (14, 77.8, 'Jam - Blackberry, 20 Ml Jar', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (15, 61.71, 'Sauce - Apple, Unsweetened', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (16, 86.09, 'Cake - Pancake', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (17, 12.85, 'Pepper - Orange', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (18, 84.63, 'Lobster - Tail, 3 - 4 Oz', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (19, 66.3, 'V8 - Vegetable Cocktail', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (20, 14.61, 'Ham - Cooked Italian', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (21, 22.75, 'Tomatoes - Diced, Canned', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (22, 97.8, 'Coconut Milk - Unsweetened', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (23, 43.31, 'Artichokes - Jerusalem', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (24, 78.24, 'Pork - Inside', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (25, 71.73, 'Veal - Liver', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (26, 43.06, 'Tomatoes - Hot House', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (27, 63.94, 'Lemonade - Strawberry, 591 Ml', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (28, 41.37, 'Bag - Bread, White, Plain', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (29, 27.76, 'Paper - Brown Paper Mini Cups', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (30, 49.54, 'Bread Base - Goodhearth', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (31, 48.23, 'Beans - Kidney, Canned', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (32, 86.64, 'Pastry - Key Limepoppy Seed Tea', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (33, 52.57, 'Wine - Black Tower Qr', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (34, 83.93, 'Bread - Dark Rye', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (35, 87.94, 'Asparagus - Mexican', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (36, 39.45, 'Coffee - French Vanilla Frothy', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (37, 19.6, 'Lid - 10,12,16 Oz', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (38, 61.54, 'Soup - Campbells Chicken', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (39, 89.88, 'Beef Ground Medium', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (40, 58.73, 'Container Clear 8 Oz', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (41, 52.97, 'Beef Wellington', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (42, 88.6, 'Steampan - Lid For Half Size', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (43, 14.1, 'Lettuce - Curly Endive', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (44, 6.04, 'Pasta - Spaghetti, Dry', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (45, 38.79, 'Lettuce - Sea / Sea Asparagus', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (46, 67.38, 'Capon - Whole', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (47, 25.88, 'Beer - Tetleys', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (48, 20.2, 'Eel Fresh', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (49, 3.97, 'Vaccum Bag - 14x20', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (50, 79.86, 'Vinegar - White', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (51, 79.91, 'Chinese Foods - Plain Fried Rice', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (52, 0.66, 'Thermometer Digital', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (53, 33.79, 'Mace Ground', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (54, 91.35, 'Nacho Chips', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (55, 99.77, 'Cheese - Cheddar, Old White', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (56, 36.92, 'Lychee', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (57, 33.17, 'Scrubbie - Scotchbrite Hand Pad', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (58, 90.17, 'Chicken - Tenderloin', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (59, 95.61, 'Turkey - Whole, Fresh', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (60, 49.92, 'Table Cloth 62x114 White', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (61, 50.88, 'Port - 74 Brights', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (62, 49.37, 'Wine - Malbec Trapiche Reserve', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (63, 22.61, 'Longos - Chicken Curried', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (64, 50.44, 'Tomatoes Tear Drop Yellow', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (65, 86.97, 'Latex Rubber Gloves Size 9', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (66, 52.25, 'Sprouts - Corn', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (67, 13.71, 'Soup Bowl Clear 8oz92008', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (68, 63.9, 'Food Colouring - Orange', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (69, 55.03, 'Orange Roughy 6/8 Oz', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (70, 53.4, 'Juice - Orange, 341 Ml', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (71, 65.23, 'Olives - Stuffed', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (72, 97.22, 'Puree - Pear', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (73, 98.92, 'Beef - Ox Tongue', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (74, 96.56, 'Veal - Liver', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (75, 21.97, 'Flour - Semolina', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (76, 62.01, 'Chicken Giblets', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (77, 24.87, 'Goat - Leg', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (78, 86.23, 'Chocolate - Milk', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (79, 96.71, 'Soup - Campbells - Chicken Noodle', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (80, 12.04, 'Cookie Chocolate Chip With', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (81, 93.42, 'Beans - Fava, Canned', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (82, 66.04, 'Spice - Montreal Steak Spice', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (83, 30.3, 'Beef - Diced', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (84, 14.93, 'Ham - Procutinni', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (85, 85.56, 'Wine - Marlbourough Sauv Blanc', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (86, 43.45, 'Beer - Blue', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (87, 28.29, 'Cheese - Feta', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (88, 34.59, 'Cheese - Stilton', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (89, 88.76, 'Curry Powder', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (90, 27.43, 'Veal Inside - Provimi', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (91, 43.74, 'Oil - Cooking Spray', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (92, 25.57, 'Bread - Pumpernickel', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (93, 86.79, 'Wine - Two Oceans Sauvignon', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (94, 90.5, 'Easy Off Oven Cleaner', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (95, 95.48, 'Beer - Guiness', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (96, 31.08, 'Jolt Cola - Electric Blue', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (97, 35.38, 'Pasta - Linguini, Dry', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (98, 67.66, 'Coffee Swiss Choc Almond', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (99, 19.71, 'Wine - Sauvignon Blanc Oyster', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (100, 17.81, 'Appetizer - Chicken Satay', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (101, 5.63, 'Pastry - Raisin Muffin - Mini', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (102, 41.01, 'Scampi Tail', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (103, 99.36, 'Artichoke - Hearts, Canned', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (104, 83.61, 'Pork - Shoulder', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (105, 44.22, 'Spic And Span All Purpose', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (106, 16.93, 'Savory', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (107, 39.25, 'Cattail Hearts', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (108, 68.4, 'Anchovy Fillets', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (109, 17.79, 'Wine - Manischewitz Concord', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (110, 22.41, 'Bread - 10 Grain', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (111, 81.34, 'Sauce - Soya, Dark', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (112, 80.0, 'Veal - Inside Round / Top, Lean', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (113, 8.24, 'Beef - Eye Of Round', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (114, 23.93, 'Cheese - Goat', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (115, 58.54, 'Clams - Canned', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (116, 75.4, 'Lettuce - Belgian Endive', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (117, 45.71, 'Seedlings - Clamshell', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (118, 85.4, 'Muffin Orange Individual', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (119, 33.63, 'Lamb - Whole, Fresh', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (120, 73.04, 'Juice - Orange, 341 Ml', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (121, 64.06, 'Beer - Moosehead', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (122, 73.57, 'Melon - Cantaloupe', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (123, 51.98, 'Bread - Pita, Mini', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (124, 50.72, 'Cheese - Oka', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (125, 66.08, 'Juice - Ocean Spray Kiwi', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (126, 80.73, 'Beef - Ground, Extra Lean, Fresh', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (127, 38.04, 'Cheese - Swiss Sliced', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (128, 26.41, 'Wine - Cotes Du Rhone', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (129, 57.86, 'Compound - Pear', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (130, 55.98, 'Banana', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (131, 74.78, 'Rabbit - Whole', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (132, 80.52, 'Lychee', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (133, 5.34, 'Chinese Lemon Pork', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (134, 32.28, 'Yams', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (135, 15.49, 'Pesto - Primerba, Paste', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (136, 94.39, 'Sauerkraut', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (137, 2.39, 'Cod - Salted, Boneless', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (138, 53.11, 'Wine - White, Schroder And Schyl', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (139, 2.72, 'Bread - 10 Grain', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (140, 15.33, 'Longos - Penne With Pesto', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (141, 44.06, 'Chickhen - Chicken Phyllo', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (142, 90.47, 'Nori Sea Weed', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (143, 60.8, 'Pimento - Canned', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (144, 62.64, 'Container - Foam Dixie 12 Oz', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (145, 70.92, 'Tea - Camomele', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (146, 4.58, 'Cheese - Comtomme', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (147, 57.62, 'Bay Leaf Fresh', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (148, 79.81, 'Pepperoni Slices', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (149, 18.08, 'Foam Tray S2', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (150, 82.96, 'Wine - Port Late Bottled Vintage', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (151, 60.47, 'Sugar - Icing', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (152, 17.58, 'Sproutsmustard Cress', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (153, 94.75, 'Soup - Clam Chowder, Dry Mix', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (154, 99.78, 'Yeast Dry - Fermipan', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (155, 92.96, 'Appetizer - Spring Roll, Veg', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (156, 92.65, 'Salt - Kosher', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (157, 59.88, 'Clam - Cherrystone', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (158, 79.04, 'Puree - Kiwi', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (159, 57.4, 'Napkin - Cocktail,beige 2 - Ply', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (160, 7.75, 'Turkey Tenderloin Frozen', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (161, 57.96, 'Salt - Celery', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (162, 24.87, 'Sloe Gin - Mcguinness', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (163, 64.85, 'Sea Bass - Fillets', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (164, 78.13, 'Wine La Vielle Ferme Cote Du', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (165, 95.74, 'Wine La Vielle Ferme Cote Du', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (166, 15.45, 'Cheese - Ricotta', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (167, 61.06, 'Anchovy In Oil', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (168, 21.92, 'Cake - Cake Sheet Macaroon', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (169, 72.22, 'Garam Masala Powder', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (170, 46.06, 'Squash - Pattypan, Yellow', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (171, 23.27, 'Lamb - Whole Head Off', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (172, 73.67, 'Wine - Red, Pinot Noir, Chateau', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (173, 87.0, 'Drambuie', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (174, 70.1, 'Wine - Chenin Blanc K.w.v.', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (175, 29.56, 'Cookie Choc', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (176, 42.71, 'Baking Powder', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (177, 9.35, 'Mangostein', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (178, 51.9, 'Lettuce - Iceberg', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (179, 61.38, 'Yogurt - Blueberry, 175 Gr', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (180, 85.39, 'Cheese - Colby', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (181, 33.41, 'Container - Hngd Cll Blk 7x7x3', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (182, 25.04, 'Puree - Mango', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (183, 93.19, 'Bread - Rosemary Focaccia', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (184, 33.3, 'Dasheen', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (185, 80.46, 'Yeast - Fresh, Fleischman', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (186, 48.98, 'Lamb - Shoulder', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (187, 49.14, 'Cookies Oatmeal Raisin', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (188, 40.47, 'Broccoli - Fresh', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (189, 19.59, 'Toamtoes 6x7 Select', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (190, 10.67, 'Bread - Calabrese Baguette', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (191, 52.56, 'Flower - Carnations', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (192, 40.19, 'Pepsi, 355 Ml', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (193, 71.55, 'Cod - Salted, Boneless', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (194, 4.72, 'Carbonated Water - Lemon Lime', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (195, 26.47, 'Sugar - Invert', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (196, 25.11, 'Beef - Ox Tongue, Pickled', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (197, 41.98, 'Jack Daniels', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (198, 20.97, 'Smoked Paprika', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (199, 66.28, 'Wine - Magnotta - Red, Baco', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (200, 89.03, 'Tomatoes - Grape', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (201, 4.45, 'Tomatoes - Roma', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (202, 35.01, 'Puree - Blackcurrant', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (203, 13.6, 'Longos - Assorted Sandwich', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (204, 21.95, 'Shrimp - Black Tiger 8 - 12', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (205, 2.37, 'Salmon Atl.whole 8 - 10 Lb', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (206, 79.66, 'Sherry - Dry', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (207, 74.43, 'Energy Drink - Franks Pineapple', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (208, 33.22, 'Chicken - Leg, Boneless', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (209, 94.58, 'Soy Protein', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (210, 25.5, 'Cactus Pads', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (211, 34.17, 'Tea - Mint', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (212, 46.69, 'Soup - Campbells, Beef Barley', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (213, 56.73, 'Soup - Knorr, Country Bean', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (214, 56.34, 'Bread - Bistro White', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (215, 79.79, 'Chocolate Eclairs', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (216, 53.8, 'Nut - Pecan, Halves', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (217, 99.13, 'Knife Plastic - White', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (218, 18.0, 'Soda Water - Club Soda, 355 Ml', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (219, 25.5, 'Cheese - Roquefort Pappillon', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (220, 89.41, 'Nectarines', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (221, 36.84, 'Broom And Broom Rack White', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (222, 19.76, 'Potatoes - Idaho 80 Count', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (223, 42.34, 'Wine - Guy Sage Touraine', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (224, 58.98, 'Gelatine Leaves - Bulk', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (225, 59.94, 'Beef - Bones, Cut - Up', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (226, 61.56, 'Chocolate - Milk', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (227, 24.84, 'Soup - Campbells, Butternut', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (228, 4.67, 'Muffins - Assorted', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (229, 79.67, 'Island Oasis - Banana Daiquiri', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (230, 21.35, 'Bok Choy - Baby', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (231, 39.67, 'Crawfish', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (232, 37.31, 'Wine - Cava Aria Estate Brut', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (233, 46.31, 'Godiva White Chocolate', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (234, 42.73, 'Napkin - Beverage 1 Ply', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (235, 35.57, 'Wine - Jafflin Bourgongone', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (236, 96.14, 'Pepper - Gypsy Pepper', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (237, 73.93, 'Oil - Shortening - All - Purpose', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (238, 2.22, 'Wine - Red, Cabernet Merlot', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (239, 62.77, 'Barramundi', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (240, 55.48, 'Cream - 35%', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (241, 61.05, 'Curry Powder Madras', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (242, 75.35, 'Fiddlehead - Frozen', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (243, 40.33, 'Chips - Assorted', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (244, 72.71, 'Beer - Camerons Cream Ale', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (245, 72.31, 'Waffle Stix', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (246, 67.41, 'Cheese - Marble', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (247, 73.47, 'Beef - Tenderloin Tails', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (248, 63.67, 'Coffee - Frthy Coffee Crisp', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (249, 6.52, 'Tea - Earl Grey', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (250, 67.55, 'Venison - Racks Frenched', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (251, 44.55, 'Muffin - Mix - Creme Brule 15l', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (252, 41.99, 'Sachet', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (253, 54.95, 'Pastry - Choclate Baked', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (254, 0.93, 'Pasta - Angel Hair', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (255, 23.55, 'Tomato - Plum With Basil', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (256, 16.9, 'Beer - Maudite', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (257, 91.01, 'Radish - Black, Winter, Organic', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (258, 93.81, 'Alize Gold Passion', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (259, 35.51, 'Pomello', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (260, 44.17, 'Iced Tea Concentrate', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (261, 81.42, 'Silicone Parch. 16.3x24.3', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (262, 13.29, 'Buffalo - Striploin', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (263, 26.53, 'Heavy Duty Dust Pan', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (264, 83.0, 'Table Cloth 54x72 White', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (265, 26.05, 'Marzipan 50/50', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (266, 34.74, 'Quail - Whole, Boneless', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (267, 79.76, 'Sauce - Caesar Dressing', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (268, 67.03, 'Pepper - Orange', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (269, 6.48, 'Pork - Suckling Pig', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (270, 62.92, 'Easy Off Oven Cleaner', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (271, 34.98, 'Tomatoes - Hot House', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (272, 21.01, 'Cookies - Englishbay Wht', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (273, 48.76, 'Aspic - Light', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (274, 63.72, 'Muffin Hinge Container 6', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (275, 15.43, 'Bread - Burger', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (276, 80.46, 'Soap - Hand Soap', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (277, 2.2, 'Cheese - Ricotta', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (278, 9.73, 'Mushroom - Portebello', 10);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (279, 18.55, 'Chicken Thigh - Bone Out', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (280, 0.93, 'Eggplant - Regular', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (281, 8.82, 'Apron', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (282, 65.78, 'Muffin Batt - Choc Chk', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (283, 14.92, 'Curry Paste - Green Masala', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (284, 47.3, 'Lobak', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (285, 71.88, 'Lamb - Whole Head Off,nz', 6);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (286, 24.62, 'Oxtail - Cut', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (287, 6.07, 'Wine - Segura Viudas Aria Brut', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (288, 8.08, 'Extract Vanilla Pure', 5);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (289, 97.71, 'Cake - Pancake', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (290, 61.2, 'Hipnotiq Liquor', 4);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (291, 87.56, 'Pomegranates', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (292, 74.94, 'Wine - White, Riesling, Semi - Dry', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (293, 92.15, 'Soup Campbells Turkey Veg.', 7);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (294, 4.08, 'Pants Custom Dry Clean', 9);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (295, 96.56, 'Tilapia - Fillets', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (296, 29.49, 'Cup - Translucent 7 Oz Clear', 2);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (297, 80.35, 'Extract - Raspberry', 8);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (298, 21.37, 'Shrimp - 150 - 250', 3);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (299, 86.59, 'Plastic Arrow Stir Stick', 1);
insert into prodotto (codice, prezzovendita, nome, numeroreparto) values (300, 86.06, 'Absolut Citron', 10);
